import 'dotenv/config';
import {test,expect} from '@playwright/test';
import {randomBytes,randomUUID} from 'node:crypto';
import {resolve} from 'node:path';
import pg from 'pg';
import bs58 from 'bs58';
import staticPlugin from '@fastify/static';
import {buildApp} from '../server/app.mjs';
import {migrate} from '../server/db.mjs';
import {registerNotifications} from '../bot/notifications.mjs';

// Browser scenarios use their own database and HTTP server, never live app data.
let maintenance,pool,app,ownedDatabase,origin,serverOffset=0;
const fixtureRulesId=randomUUID();
const telegramMessages=[];
const config={jwtSecret:randomBytes(32).toString('hex'),botApiSecret:randomBytes(32).toString('hex'),adminTgIds:[900001],authJwtTtlSeconds:1800,botUsername:'PreviewTournamentBot',localDemo:false,notifyTransport:async message=>{telegramMessages.push(message);return {ok:true,message_id:telegramMessages.length};},editTransport:async()=>({ok:true})};
async function post(path,body){
 if(path==='/auth/register')body={...body,rules_accepted:true,rules_version_id:fixtureRulesId};
 const r=await fetch(origin+'/api/v1'+path,{method:'POST',headers:{'content-type':'application/json','x-bot-secret':config.botApiSecret},body:JSON.stringify(body)});
 const result=await r.json();
 if(path==='/bot/code'&&r.status===429&&result.error?.code==='CODE_COOLDOWN'){
  serverOffset+=result.retry_after_seconds*1000;
  return post(path,body);
 }
 if(!r.ok)throw Error('Fixture API failed: '+path+' ('+r.status+')');
 return result;
}
test.beforeEach(()=>{serverOffset+=90000;});
test.beforeAll(async()=>{
 const connection=new URL(process.env.DATABASE_URL);connection.pathname='/postgres';
 maintenance=new pg.Pool({connectionString:connection.href});
 ownedDatabase='codex_browser_'+randomUUID().replaceAll('-','');
 if(!/^codex_browser_[a-f0-9]{32}$/.test(ownedDatabase))throw Error('Invalid test database');
 await maintenance.query('CREATE DATABASE "'+ownedDatabase+'"');connection.pathname='/'+ownedDatabase;
 pool=new pg.Pool({connectionString:connection.href});await migrate(pool);
 await pool.query("INSERT INTO tournament_rules(id,title,body,status,published_at,created_at) VALUES($1,$2,$3,'ACTIVE',now(),now())",[fixtureRulesId,'Тестовые правила','Правила тестового турнира. Результаты публикует администратор.']);
 for(let i=1;i<=40;i++)await pool.query('INSERT INTO initial_users(tg_id,group_name) VALUES($1,$2)',[100000+i,'Тестовый реестр']);
 await pool.query('INSERT INTO initial_users(tg_id,group_name) VALUES(900001,$1)',['Администратор']);
 app=buildApp({pool,config,clock:()=>new Date(Date.now()+serverOffset)});registerNotifications(app,pool,config);await app.register(staticPlugin,{root:resolve('dist')});
 app.setNotFoundHandler((req,reply)=>req.method==='GET'&&!req.url.startsWith('/api/')?reply.sendFile('index.html'):reply.code(404).send({error:{code:'NOT_FOUND'}}));
 origin=await app.listen({host:'127.0.0.1',port:0});
 const session=await post('/auth/register',{display_name:'PreviewAdmin'});
 const grant=await post('/bot/code',{tg_id:900001,tg_username:'PreviewAdmin'});
 await post('/auth/code/verify',{token:session.token,telegram_identifier:'@PreviewAdmin',code:grant.code});
});
test.afterAll(async()=>{
 await app?.close();await pool?.end();
 if(maintenance){try{if(ownedDatabase&&/^codex_browser_[a-f0-9]{32}$/.test(ownedDatabase))await maintenance.query('DROP DATABASE "'+ownedDatabase+'" WITH (FORCE)');}finally{await maintenance.end();}}
});

async function enterCode(page,id,username){
 const dialog=page.getByRole('dialog');
 // Manual Start is the fallback after the automatic request finishes.
 // Starting both concurrently can intentionally replace the earlier OTP.
 await expect(dialog.getByText('Запрос кода выполнен. Если бот уже запущен, код придёт автоматически.')).toBeVisible();
 const grant=await post('/bot/code',{tg_id:id,tg_username:username});
 await expect(dialog.locator('.telegram-bot-address')).toContainText('@PreviewTournamentBot');
 await expect(dialog.getByRole('link',{name:'Открыть бота в Telegram'})).toHaveAttribute('href','https://t.me/PreviewTournamentBot');
 await dialog.getByLabel('Код из Telegram').fill(grant.code);
 await dialog.getByRole('button',{name:'Подтвердить код'}).click();
 await expect(dialog).toHaveCount(0);
}

test('desktop: code registration, wallet without UID, admin approval, scoring and guest leaderboard',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(origin);
 await expect(page.getByLabel('Демонстрационный аккаунт')).toHaveCount(0);
 await expect(page.getByRole('heading',{level:1})).toContainText('$MET Meteora Liquidity Provider');
 await expect(page.locator('.gift-demo-banner')).toContainText('ДЕМО');
 await expect(page.locator('.gift-demo-banner')).toContainText('Техника Apple на XXX $');
 await page.getByRole('button',{name:'Открыть публичный лидерборд'}).click();
 await expect(page.getByText('Нет допущенных участников')).toBeVisible();
 await page.getByRole('button',{name:/На страницу входа/}).click();
 await expect(page.locator('.public-stats').getByRole('button',{name:'В лидерборд',exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Регистрация на турнир',exact:true}).click();
 let dialog=page.getByRole('dialog');
 await dialog.getByLabel('Имя в турнире').fill('PreviewTrader');
 await dialog.getByLabel('Telegram username или ID').fill('@PreviewTrader');
 await dialog.getByRole('checkbox',{name:'Я ознакомился и согласен с правилами турнира'}).check();
 await dialog.getByRole('button',{name:'Получить код через Telegram'}).click();
 await expect(dialog.getByLabel('Код из Telegram')).toBeVisible();
 await dialog.getByLabel('Код из Telegram').fill('000123');
 await expect(dialog.getByLabel('Код из Telegram')).toHaveValue('000123');
 expect(await page.evaluate(()=>Object.hasOwn(JSON.parse(sessionStorage.getItem('meteora-pending')),'code'))).toBe(false);
 await enterCode(page,100001,'PreviewTrader');
 await expect(page.getByRole('heading',{name:'Привет, PreviewTrader'})).toBeVisible();
 await expect(page.getByRole('button',{name:'Админка',exact:true})).toHaveCount(0);
 const partner=page.getByLabel('Указать UID аккаунта на бирже');
 await expect(partner).toBeChecked();
 await expect(page.getByLabel('UID аккаунта на бирже',{exact:true})).toHaveAttribute('required','');
 await expect(page.getByLabel('Хэш вывода с биржи')).toHaveAttribute('required','');
 await expect(page.getByText('Заполните UID аккаунта на бирже или отключите участие в Special Gift.')).toBeVisible();
 await page.getByLabel('Адрес кошелька Solana').fill('11111111111111111111111111111111');
 const walletRequests=[];page.on('request',request=>{if(request.method()==='POST'&&new URL(request.url()).pathname==='/api/v1/user/wallet')walletRequests.push(request.postDataJSON());});
 await page.getByRole('button',{name:'Сохранить профиль'}).click();
 expect(await page.getByLabel('UID аккаунта на бирже',{exact:true}).evaluate(input=>input.validity.valueMissing)).toBe(true);
 expect(walletRequests).toEqual([]);
 await page.getByLabel('UID аккаунта на бирже',{exact:true}).fill('000000000');
 await page.getByRole('button',{name:'Сохранить профиль'}).click();
 expect(await page.getByLabel('Хэш вывода с биржи').evaluate(input=>input.validity.valueMissing)).toBe(true);
 expect(walletRequests).toEqual([]);
 await partner.uncheck();
 await expect(page.getByRole('region',{name:'Участие без Special Gift'})).toContainText('отказываетесь от участия за специальные призы');
 await expect(page.getByRole('region',{name:'Участие без Special Gift'})).toContainText('можете продолжить турнир');
 await expect(page.getByLabel('Хэш вывода с биржи')).toHaveCount(0);
 await page.getByRole('button',{name:'Сохранить профиль'}).click();
 await expect(page.getByRole('status')).toHaveText('Профиль сохранён');
 expect(walletRequests[0]).toMatchObject({exchange_uid:null,withdrawal_tx_hash:null});
 await expect(page.getByText('На проверке',{exact:true})).toBeVisible();
 await page.reload();
 await expect(page.getByRole('heading',{name:'Привет, PreviewTrader'})).toBeVisible();
 await expect(partner).not.toBeChecked();
 await expect(page.getByLabel('UID аккаунта на бирже',{exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:/Выйти/}).click();
 await page.getByLabel('Telegram username или ID').fill('@PreviewAdmin');
 await page.getByRole('button',{name:'Получить код через Telegram'}).click();
 await enterCode(page,900001,'PreviewAdmin');
 await expect(page.getByRole('heading',{name:'Админка',exact:true})).toBeVisible();
 const participant=page.locator('.admin-user').filter({hasText:'PreviewTrader'});
 await participant.locator('summary').click();
 await participant.getByRole('button',{name:'Подтвердить',exact:true}).click();
 await expect(participant.getByText('Подтверждено',{exact:true})).toBeVisible();
 const sections=page.getByRole('navigation',{name:'Разделы базы данных'});
 await expect(sections.getByRole('button')).toHaveCount(8);
 await sections.getByRole('button',{name:/^Результаты/}).click();
 await page.getByLabel('Файл результатов').setInputFiles({name:'scores.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({rows:[{tg_id:100001,pnl:'2000.000000',initial_capital:'1000.000000',current_capital:'3000.000000',lp_volume:'50.000000',roi_percentage:200}]}))});
 await page.getByRole('button',{name:'Загрузить данные'}).click();
 await expect(page.locator('.toast[role="status"]')).toContainText('Импорт завершён');
 await expect(page.locator('.admin-data-table tbody tr')).toHaveCount(1);
 await page.getByRole('button',{name:'Лидерборд',exact:true}).click();
 await expect(page.locator('tbody tr')).toContainText('PreviewTrader');
 await expect(page.locator('tbody tr')).toContainText('2\u202f000,000000');
 await expect(page.locator('tbody tr')).toContainText('RespectGift');
 await page.getByRole('button',{name:/Выйти/}).click();
 const publicStats=await (await fetch(origin+'/api/v1/public/stats')).json();
 expect(publicStats.participant_count).toBe(1);
 expect(publicStats.current_capital).toBe('3000.000000');
 expect(publicStats.pnl).toBe('2000.000000');
 expect(publicStats.lp_volume).toBe('50.000000');
 await expect(page.getByText('Оборот LP',{exact:true})).toBeVisible();
 await expect(page.locator('.public-stats')).toContainText('50');
 await page.getByRole('button',{name:'Открыть публичный лидерборд'}).click();
 await expect(page.locator('tbody tr')).toContainText('PreviewTrader');
 expect(errors).toEqual([]);
});

test('mobile: numeric ID, restored code session, eight admin sections, search, pagination and persisted settings',async({page})=>{
 await page.setViewportSize({width:390,height:844});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(origin);
 await page.getByLabel('Telegram username или ID').fill('900001');
 await page.getByRole('button',{name:'Получить код через Telegram'}).click();
 await expect(page.getByRole('dialog').getByText('Запрос кода выполнен. Если бот уже запущен, код придёт автоматически.')).toBeVisible();
 const grant=await post('/bot/code',{tg_id:900001,tg_username:null});
 await page.getByRole('dialog').getByLabel('Код из Telegram').fill(grant.code);
 await page.reload();
 const dialog=page.getByRole('dialog');
 await expect(dialog.getByLabel('Telegram username или ID')).toHaveValue('900001');
 await expect(dialog.getByLabel('Код из Telegram')).toHaveValue('');
 await dialog.getByLabel('Код из Telegram').fill(grant.code);
 await dialog.getByRole('button',{name:'Подтвердить код'}).click();
 await expect(page.getByRole('heading',{name:'Админка',exact:true})).toBeVisible();
 const sections=page.getByRole('navigation',{name:'Разделы базы данных'});
 await expect(sections.getByRole('button')).toHaveCount(8);
 await sections.getByRole('button',{name:/^Реестр допуска/}).click();
 await expect(page.locator('.admin-data-table tbody tr')).toHaveCount(25);
 await page.getByRole('button',{name:'Далее',exact:true}).click();
 await expect(page.locator('.admin-data-pagination')).toContainText('Страница 2');
 await page.waitForTimeout(450); // Initial search debounce must not reset the selected page.
 await expect(page.locator('.admin-data-pagination')).toContainText('Страница 2');
 await page.getByLabel('Поиск по данным раздела').fill('   ');
 await page.waitForTimeout(450); // An unchanged normalized query must keep pagination.
 await expect(page.locator('.admin-data-pagination')).toContainText('Страница 2');
 await page.getByLabel('Поиск по данным раздела').fill('100001');
 await expect(page.locator('.admin-data-table tbody tr')).toHaveCount(1);
 for(const name of [/^Кошельки/,/^UID и награды/,/^Результаты/,/^Сессии входа/]){
  await sections.getByRole('button',{name}).click();
  await expect(page.locator('.admin-data-pagination')).toContainText('Всего записей:');
  await expect(page.getByRole('alert')).toHaveCount(0);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 }
 await sections.getByRole('button',{name:'Настройки турнира'}).click();
 const values={'Начало регистрации':'2030-05-01T09:00','Конец регистрации':'2030-05-10T11:00','Начало турнира':'2030-05-10T12:00','Конец турнира':'2030-05-17T12:00'};
 for(const[label,value]of Object.entries(values)){const [date,time]=value.split('T');await page.getByLabel(label+' · дата',{exact:true}).fill(date);await page.getByLabel(label+' · время (UTC)',{exact:true}).fill(time);}
 await page.getByRole('button',{name:'Сохранить расписание'}).click();
 await expect(page.getByRole('status')).toHaveText('Расписание сохранено');
 const upcoming=await (await fetch(origin+'/api/v1/public/tournament')).json();
 expect(upcoming.registration_status).toBe('UPCOMING');
 expect(upcoming.start_at).toBe('2030-05-10T12:00:00.000Z');
 const guest=await page.context().browser().newContext({viewport:{width:390,height:844}});
 try{
  const guestPage=await guest.newPage();await guestPage.goto(origin);
  await expect(guestPage.getByRole('button',{name:'Новый участник? Регистрация'})).toBeDisabled();
  await expect(guestPage.getByLabel('Telegram username или ID')).toBeEnabled();
  await expect(guestPage.getByText('Регистрация ещё не началась').first()).toBeVisible();
  await expect(guestPage.locator('.public-stats')).toBeVisible();
  await expect(guestPage.getByRole('region',{name:'Сроки турнира'})).toContainText('UTC');
  await expect(guestPage.getByRole('region',{name:'Сроки турнира'})).toContainText('12:00');
  await expect(guestPage.getByText('America/Los_Angeles',{exact:false})).toHaveCount(0);
  expect(await guestPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 }finally{await guest.close();}
 await page.reload();
 await page.getByRole('navigation',{name:'Разделы базы данных'}).getByRole('button',{name:'Настройки турнира'}).click();
 for(const[label,value]of Object.entries(values)){const [date,time]=value.split('T');await expect(page.getByLabel(label+' · дата',{exact:true})).toHaveValue(date);await expect(page.getByLabel(label+' · время (UTC)',{exact:true})).toHaveValue(time);}
 for(const label of Object.keys(values))await page.getByRole('button',{name:'Очистить · '+label.toLowerCase(),exact:true}).click();
 await page.getByRole('button',{name:'Сохранить расписание'}).click();
 await expect(page.getByRole('status')).toHaveText('Расписание сохранено');
 for(const label of Object.keys(values)){await expect(page.getByLabel(label+' · дата',{exact:true})).toHaveValue('');await expect(page.getByLabel(label+' · время (UTC)',{exact:true})).toHaveValue('');}
 expect(errors).toEqual([]);
});

test('automatic admin code, external admission notice and identity, session across leaderboard, reload, tabs and 16 minutes',async({page,browser})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 let externalContext,secondTab;
 try{
  await page.goto(origin);
  const before=telegramMessages.length;
  await page.getByLabel('Telegram username или ID').fill('900001');
  await page.getByRole('button',{name:'Получить код через Telegram'}).click();
  await expect.poll(()=>telegramMessages.slice(before).some(m=>m.chat_id===900001&&/^Код для входа: \d{6}/.test(m.text))).toBe(true);
  const delivered=telegramMessages.slice(before).find(m=>m.chat_id===900001&&/^Код для входа: \d{6}/.test(m.text));
  const dialog=page.getByRole('dialog');
  await expect(dialog).toContainText('автоматически');
  await dialog.getByLabel('Код из Telegram').fill(delivered.text.match(/^Код для входа: (\d{6})/)[1]);
  await dialog.getByRole('button',{name:'Подтвердить код'}).click();
  await expect(page.getByRole('heading',{name:'Админка',exact:true})).toBeVisible();

  externalContext=await browser.newContext({viewport:{width:390,height:844}});
  const external=await externalContext.newPage();external.on('pageerror',e=>errors.push(e.message));
  await external.goto(origin);
  await external.getByRole('button',{name:'Новый участник? Регистрация'}).click();
  const registration=external.getByRole('dialog');
  await registration.getByLabel('Имя в турнире').fill('ExternalTrader');
  await registration.getByLabel('Telegram username или ID').fill('@ExternalTrader');
  await registration.getByRole('checkbox',{name:'Я ознакомился и согласен с правилами турнира'}).check();
  await registration.getByRole('button',{name:'Получить код через Telegram'}).click();
  await enterCode(external,940002,'ExternalTrader');
  await expect(external.getByText(/Вы пока не допущены к турниру/)).toBeVisible();
  await expect(external.getByRole('link',{name:'@LeoCryptus',exact:true})).toHaveAttribute('href','https://t.me/LeoCryptus');
  await expect(external.getByRole('link',{name:'@D_mOnII',exact:true})).toHaveAttribute('href','https://t.me/D_mOnII');
  await expect.poll(()=>telegramMessages.some(m=>m.chat_id===940002&&m.text.includes('не допущены')&&m.text.includes('@LeoCryptus'))).toBe(true);
  expect(await external.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);

  await page.getByRole('button',{name:'Лидерборд',exact:true}).click();
  await page.getByRole('button',{name:'Админка',exact:true}).click();
  await page.getByLabel('Поиск участника').fill('@ExternalTrader');
  const card=page.locator('.admin-user').filter({hasText:'ExternalTrader'});
  await expect(card).toHaveCount(1);
  await expect(card.locator('summary')).toContainText('@ExternalTrader');
  await expect(card.locator('summary')).toContainText('940002');
  await card.locator('summary').click();
  await expect(card).toContainText('Имя участника');
  await expect(card).toContainText('Telegram username');
  await expect(card).toContainText('Telegram ID');
  await page.getByRole('button',{name:'Обновить список',exact:true}).click();
  await expect(card).toBeVisible();

  const repeatedAuth=[];
  page.on('request',r=>{const path=new URL(r.url()).pathname;if(path.startsWith('/api/v1/auth/')&&path!=='/api/v1/auth/access')repeatedAuth.push(path);});
  await page.getByRole('button',{name:'Лидерборд',exact:true}).click();
  await expect(page.getByRole('button',{name:/Выйти/})).toBeVisible();
  await page.getByRole('button',{name:'Личный кабинет',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Привет, PreviewAdmin'})).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading',{name:'Админка',exact:true})).toBeVisible();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.clock.install();
  serverOffset+=16*60000;
  await page.clock.setFixedTime(new Date(Date.now()+16*60000));
  await page.reload();
  await expect(page.getByRole('heading',{name:'Админка',exact:true})).toBeVisible();
  secondTab=await page.context().newPage();
  await secondTab.goto(origin);
  await expect(secondTab.getByRole('heading',{name:'Админка',exact:true})).toBeVisible();
  await expect(secondTab.getByRole('dialog')).toHaveCount(0);
  expect(repeatedAuth).toEqual([]);
  await page.getByRole('button',{name:/Выйти/}).click();
  await expect(secondTab.getByRole('heading',{name:'С возвращением'})).toBeVisible();
  expect(await page.evaluate(()=>localStorage.getItem('meteora-token'))).toBeNull();
  expect(errors).toEqual([]);
 }finally{await secondTab?.close();await externalContext?.close();}
});

test('25-minute banner, Telegram confirmation renews without code, then silence expires the session',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(origin);
 await page.getByRole('button',{name:'Новый участник? Регистрация'}).click();
 const dialog=page.getByRole('dialog');
 await dialog.getByLabel('Имя в турнире').fill('SessionTrader');
 await dialog.getByLabel('Telegram username или ID').fill('SessionTrader');
 await dialog.getByRole('checkbox',{name:'Я ознакомился и согласен с правилами турнира'}).check();
 await dialog.getByRole('button',{name:'Получить код через Telegram'}).click();
 await enterCode(page,7265947400,'SessionTrader');
 await expect(page.getByRole('heading',{name:'Привет, SessionTrader'})).toBeVisible();
 const first=await page.evaluate(()=>JSON.parse(atob(localStorage.getItem('meteora-token').split('.')[1])));
 expect(first.exp-first.iat).toBe(1800);
 const banner=page.getByRole('complementary',{name:'Продление сессии'});
 await expect(banner).toHaveCount(0);
 await page.clock.install();
 serverOffset+=25*60000;
 await page.clock.setSystemTime(new Date(Date.now()+25*60000));
 // Reload asks the server for the exact remaining time and cannot prolong it.
 await page.reload();
 await expect(banner).toBeVisible();
 await expect(banner).toContainText('без повторного входа');
 await banner.getByRole('button',{name:'Продолжить через Telegram'}).click();
 await expect(banner).toContainText('Подтвердить сессию на сайте');
 const challenge=telegramMessages.findLast(m=>m.chat_id===7265947400&&m.reply_markup);
 expect(challenge.reply_markup.inline_keyboard[0][0].text).toBe('Подтвердить сессию на сайте');
 const confirmation=challenge.reply_markup.inline_keyboard[0][0].callback_data.slice(3);
 const before=await page.evaluate(()=>JSON.parse(atob(localStorage.getItem('meteora-token').split('.')[1])));
 expect(before.exp).toBe(first.exp);
 const requestDeadline=(await pool.query('SELECT renewal_expires_at FROM auth_sessions WHERE id=$1',[first.jti])).rows[0].renewal_expires_at;
 expect(+new Date(requestDeadline)-Date.now()-serverOffset).toBeLessThanOrEqual(300000);
 await post('/bot/session/confirm',{token:confirmation,tg_id:7265947400});
 await page.clock.runFor(4000);
 await expect(banner).toHaveCount(0,{timeout:10000});
 await expect(page.getByRole('heading',{name:'Привет, SessionTrader'})).toBeVisible();
 await expect(page.getByRole('dialog')).toHaveCount(0);
 const renewed=await page.evaluate(()=>JSON.parse(atob(localStorage.getItem('meteora-token').split('.')[1])));
 expect(renewed.jti).toBe(first.jti);
 expect(renewed.exp).toBeGreaterThan(first.exp);
 expect(renewed.exp-renewed.iat).toBe(1800);
 await page.setViewportSize({width:390,height:844});
 serverOffset+=25*60000;
 await page.clock.setSystemTime(new Date(Date.now()+50*60000));
 await page.reload();
 await expect(banner).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:'.local/session-banner-v0.7.png',fullPage:true});
 await banner.getByRole('button',{name:'Продолжить через Telegram'}).click();
 await expect(banner).toContainText('Подтвердить сессию на сайте');
 serverOffset+=5*60000+1000;
 await page.clock.setSystemTime(new Date(Date.now()+55*60000+1000));
 await page.reload();
 await expect(page.getByRole('dialog')).toBeVisible();
 await expect(page.getByRole('dialog').getByLabel('Код из Telegram')).toHaveCount(0);
 expect(await page.evaluate(()=>localStorage.getItem('meteora-token'))).toBeNull();
 expect(errors).toEqual([]);
});

test('username normalization and resend countdown lasts 90 seconds through reload',async({page})=>{
 await page.goto(origin);
 await page.getByLabel('Telegram username или ID').fill(' @PreviewAdmin ');
 await page.getByRole('button',{name:'Получить код через Telegram'}).click();
 const dialog=page.getByRole('dialog');
 await expect(dialog.getByLabel('Telegram username или ID')).toHaveValue('PreviewAdmin');
 await expect(dialog.getByText('Запрос кода выполнен. Если бот уже запущен, код придёт автоматически.')).toBeVisible();
 const resend=dialog.getByRole('button',{name:/Повтор|Отправить код повторно/});
 await expect(resend).toBeDisabled();
 await page.reload();
 await expect(resend).toBeDisabled();
 const resendAt=await page.evaluate(()=>JSON.parse(sessionStorage.getItem('meteora-pending')).code_resend_at);
 await page.clock.install({time:new Date(resendAt-90000)});
 await page.clock.fastForward(89000);
 await expect(resend).toBeDisabled();
 serverOffset+=90000;
 await page.clock.fastForward(2000);
 await expect(dialog.getByRole('button',{name:'Отправить код повторно',exact:true})).toBeEnabled();
 await dialog.getByRole('button',{name:'Отправить код повторно',exact:true}).click();
 await expect(resend).toBeDisabled();
});

test('public tournament wording and automatic timeline phases',async({page})=>{
 const base=Date.parse('2030-05-01T09:00:00Z');let phase=0;
 await page.clock.install({time:new Date(base)});
 await page.route('**/api/v1/public/tournament',route=>route.fulfill({json:{
  registration_start_at:null,registration_end_at:new Date(base+60000).toISOString(),
  start_at:new Date(base+120000).toISOString(),end_at:new Date(base+180000).toISOString(),
  registration_open:phase===0,registration_status:phase===0?'OPEN':'CLOSED',
  started:phase>=2,ended:phase>=3,server_time:new Date(base+phase*60000).toISOString(),
 }}));
 await page.goto(origin);
 const timeline=page.getByRole('region',{name:'Сроки турнира'});
 await expect(timeline.getByText('Регистрация до',{exact:true})).toBeVisible();
 await expect(timeline.getByText('Начало турнира',{exact:true})).toBeVisible();
 await expect(timeline.getByText('Окончание турнира',{exact:true})).toBeVisible();
 await expect(page.getByRole('heading',{name:'Показатели в турнире'})).toBeVisible();
 await expect(page.locator('.public-stats')).toContainText('Участников в турнире');
 await expect(page.locator('.public-stats')).toContainText('Капитал в турнире');
 expect(await timeline.evaluate(element=>element.compareDocumentPosition(document.querySelector('.public-stats'))&Node.DOCUMENT_POSITION_FOLLOWING)).toBeTruthy();
 phase=1;await page.clock.fastForward(60100);
 await expect(timeline.getByText('Регистрация до',{exact:true})).toHaveCount(0);
 await expect(timeline.getByText('Начало турнира',{exact:true})).toBeVisible();
 await expect(timeline.getByText('Окончание турнира',{exact:true})).toBeVisible();
 phase=2;await page.clock.fastForward(60100);
 await expect(timeline.getByText('Турнир до',{exact:true})).toBeVisible();
 await expect(timeline.getByText('Начало турнира',{exact:true})).toHaveCount(0);
 await expect(timeline.getByText('Окончание турнира',{exact:true})).toHaveCount(0);
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 phase=3;await page.clock.fastForward(60100);
 await expect(timeline).toContainText('Турнир завершён');
 await expect(timeline.getByText('Турнир до',{exact:true})).toHaveCount(0);
});

test('wallet and UID duplicates appear before save, clear on edit and allow own saved values',async({page})=>{
 const ownerId=randomUUID(),ownerAddress=bs58.encode(randomBytes(32)),newAddress=bs58.encode(randomBytes(32));
 await pool.query("INSERT INTO users(id,tg_id,display_name,registration_status,admin_notes) VALUES($1,100089,'DuplicateOwner','APPROVED_MANUAL','Browser fixture')",[ownerId]);
 await pool.query("INSERT INTO wallets(id,user_id,wallet_address,withdrawal_tx_hash,validation_status) VALUES($1,$2,$3,'fixture','VALID')",[randomUUID(),ownerId,ownerAddress]);
 await pool.query("INSERT INTO partner_rewards(user_id,reward_type,exchange_uid,uid_status) VALUES($1,'PARTNER_GIFTS','000000000','VALID')",[ownerId]);
 await page.goto(origin);
 await page.getByRole('button',{name:'Регистрация на турнир',exact:true}).click();
 const dialog=page.getByRole('dialog');
 await dialog.getByLabel('Имя в турнире').fill('DuplicateProbe');
 await dialog.getByLabel('Telegram username или ID').fill('DuplicateProbe');
 await dialog.getByRole('checkbox',{name:'Я ознакомился и согласен с правилами турнира'}).check();
 await dialog.getByRole('button',{name:'Получить код через Telegram'}).click();
 await enterCode(page,100090,'DuplicateProbe');
 await expect(page.getByRole('heading',{name:'Привет, DuplicateProbe'})).toBeVisible();
 let releaseCheck;const checkGate=new Promise(resolve=>{releaseCheck=resolve;});
 await page.route('**/api/v1/user/profile-check',async route=>{await checkGate;await route.continue();});
 await page.getByLabel('Адрес кошелька Solana').fill(ownerAddress);
 await page.getByLabel('UID аккаунта на бирже',{exact:true}).fill('000000000');
 await expect(page.getByText('Проверяем на дубликаты…',{exact:true})).toHaveCount(2);
 await expect(page.getByRole('button',{name:'Сохранить профиль'})).toBeDisabled();
 releaseCheck();
 await expect(page.getByText('Этот кошелёк уже зарегистрирован другим участником',{exact:true})).toBeVisible();
 await expect(page.getByText('Этот UID уже зарегистрирован другим участником',{exact:true})).toBeVisible();
 await expect(page.getByLabel('Хэш вывода с биржи')).toHaveValue('');
 await expect(page.getByRole('button',{name:'Сохранить профиль'})).toBeDisabled();
 await expect(page.getByLabel('UID аккаунта на бирже',{exact:true})).toHaveAttribute('aria-invalid','true');
 expect((await pool.query('SELECT w.* FROM wallets w JOIN users u ON u.id=w.user_id WHERE u.tg_id=100090')).rowCount).toBe(0);
 await page.getByLabel('Адрес кошелька Solana').fill('not-a-solana-address');
 await expect(page.locator('#availability-wallet_address')).toContainText('Неверный формат');
 await expect(page.getByRole('button',{name:'Сохранить профиль'})).toBeDisabled();
 await expect(page.getByLabel('Адрес кошелька Solana')).toHaveAttribute('aria-invalid','true');
 await page.getByLabel('Адрес кошелька Solana').fill(newAddress);
 await page.getByLabel('UID аккаунта на бирже',{exact:true}).fill('00012345090');
 await expect(page.getByText('Проверено: дубликатов нет',{exact:true})).toHaveCount(2);
 await expect(page.getByText('Этот кошелёк уже зарегистрирован другим участником',{exact:true})).toHaveCount(0);
 await expect(page.getByText('Этот UID уже зарегистрирован другим участником',{exact:true})).toHaveCount(0);
 await page.getByLabel('Хэш вывода с биржи').fill('fixture-new-withdrawal');
 await page.getByRole('button',{name:'Сохранить профиль'}).click();
 await expect(page.locator('.toast[role="status"]')).toContainText('Профиль сохранён');
 await page.reload();
 await expect(page.getByRole('heading',{name:'Привет, DuplicateProbe'})).toBeVisible();
 await expect(page.getByText('Проверено: дубликатов нет',{exact:true})).toHaveCount(2);
 await expect(page.getByRole('button',{name:'Сохранить профиль'})).toBeEnabled();
 const saved=(await pool.query('SELECT w.wallet_address,r.exchange_uid FROM users u JOIN wallets w ON w.user_id=u.id JOIN partner_rewards r ON r.user_id=u.id WHERE u.tg_id=100090')).rows[0];
 expect(saved).toEqual({wallet_address:newAddress,exchange_uid:'00012345090'});
 // Simulate a value taken after the precheck: final server conflict belongs under the field.
 await page.route('**/api/v1/user/profile-check',route=>route.fulfill({json:{wallet_address:{available:true},exchange_uid:{available:true}}}),{times:1});
 await page.getByLabel('UID аккаунта на бирже',{exact:true}).fill('000000000');
 await expect(page.getByText('Проверено: дубликатов нет',{exact:true})).toHaveCount(2);
 await page.getByRole('button',{name:'Сохранить профиль'}).click();
 await expect(page.locator('#availability-exchange_uid')).toContainText('Этот UID уже зарегистрирован другим участником');
 await expect(page.locator('.profile-form [role="alert"]')).toHaveCount(0);
 await expect(page.getByRole('button',{name:'Сохранить профиль'})).toBeDisabled();
 expect((await pool.query('SELECT exchange_uid FROM partner_rewards r JOIN users u ON u.id=r.user_id WHERE u.tg_id=100090')).rows[0].exchange_uid).toBe('00012345090');
});

test('rules consent, preserved registration form, admin publication, public archive and explicit removal',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.setViewportSize({width:390,height:844});
 await page.goto(origin);
 await page.getByRole('button',{name:'Регистрация на турнир',exact:true}).click();
 const auth=page.getByRole('dialog',{name:'Подтверждение Telegram'});
 await auth.getByLabel('Имя в турнире').fill('RulesTrader');
 await auth.getByLabel('Telegram username или ID').fill('@RulesTrader');
 const consent=auth.getByRole('checkbox',{name:'Я ознакомился и согласен с правилами турнира'});
 await expect(consent).not.toBeChecked();
 await expect(auth.getByRole('button',{name:'Получить код через Telegram'})).toBeDisabled();
 await auth.getByRole('button',{name:/Правила · версия/}).click();
 const reader=page.getByRole('dialog',{name:'Правила турнира'});
 await expect(reader).toContainText('Результаты публикует администратор.');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.keyboard.press('Escape');
 await expect(reader).toHaveCount(0);
 await expect(auth.getByLabel('Имя в турнире')).toHaveValue('RulesTrader');
 await expect(auth.getByLabel('Telegram username или ID')).toHaveValue('@RulesTrader');
 await consent.check();
 await auth.getByRole('button',{name:/Правила · версия/}).click();
 await reader.getByRole('button',{name:'Закрыть правила'}).click();
 await expect(consent).toBeChecked();
 await auth.getByRole('button',{name:'Получить код через Telegram'}).click();
 await expect(auth.getByText('Запрос кода выполнен. Если бот уже запущен, код придёт автоматически.')).toBeVisible();
 const obsoleteGrant=await post('/bot/code',{tg_id:100091,tg_username:'RulesTrader'});
 await page.route('**/api/v1/auth/code/verify',route=>route.fulfill({status:409,json:{error:{code:'RULES_CHANGED',message:'Rules changed',fields:[]}}}),{times:1});
 await auth.getByLabel('Код из Telegram').fill(obsoleteGrant.code);
 await auth.getByRole('button',{name:'Подтвердить код'}).click();
 await expect(reader).toBeVisible();
 await reader.getByRole('button',{name:'Закрыть правила'}).click();
 await expect(auth.getByLabel('Имя в турнире')).toHaveValue('RulesTrader');
 await expect(auth.getByLabel('Telegram username или ID')).toHaveValue('@RulesTrader');
 await expect(consent).not.toBeChecked();
 const replacementRequests=[];page.on('request',r=>{if(new URL(r.url()).pathname==='/api/v1/auth/code/request')replacementRequests.push(r.url());});
 await consent.check();
 await auth.getByRole('button',{name:'Получить код через Telegram'}).click();
 await expect(auth.getByLabel('Код из Telegram')).toBeVisible();
 // Reuse the unconsumed OTP after accepting again: no second Telegram issuance.
 await auth.getByLabel('Код из Telegram').fill(obsoleteGrant.code);
 await auth.getByRole('button',{name:'Подтвердить код'}).click();
 await expect(auth).toHaveCount(0);
 expect(replacementRequests).toEqual([]);
 const accepted=(await pool.query('SELECT accepted_rules_version_id,rules_accepted_at FROM users WHERE tg_id=100091')).rows[0];
 expect(accepted.accepted_rules_version_id).toBe(fixtureRulesId);expect(accepted.rules_accepted_at).toBeTruthy();
 await page.getByRole('button',{name:/Выйти/}).click();
 const adminPending=await post('/auth/login',{});
 await post('/bot/verify',{token:adminPending.token,tg_id:900001,tg_username:'PreviewAdmin'});
 const adminAccess=await (await fetch(origin+'/api/v1/auth/session/'+adminPending.token)).json();
 await page.evaluate(token=>localStorage.setItem('meteora-token',token),adminAccess.access_token);
 await page.reload();
 await expect(page.getByRole('heading',{name:'Админка',exact:true})).toBeVisible();
 const sections=page.getByRole('navigation',{name:'Разделы базы данных'});
 await sections.getByRole('button',{name:/^Правила/}).click();
 await page.getByLabel('Заголовок правил').fill('Новая редакция тестовых правил');
 const literal='Текст новой редакции\n<script>window.rulesExecuted=true</script>';
 await page.getByLabel('Загрузить текст правил').setInputFiles({name:'rules.md',mimeType:'text/markdown',buffer:Buffer.from(literal)});
 await expect(page.getByLabel('Текст правил',{exact:true})).toHaveValue(literal);
 await page.getByRole('button',{name:'Сохранить черновик',exact:true}).click();
 await expect(page.getByRole('button',{name:'Опубликовать правила'})).toBeEnabled();
 const publicBefore=await (await fetch(origin+'/api/v1/public/rules')).json();expect(publicBefore.versions).toHaveLength(1);
 page.on('dialog',dialog=>dialog.accept());
 await page.getByRole('button',{name:'Опубликовать правила'}).click();
 await expect(page.getByLabel('Текст правил',{exact:true})).toHaveAttribute('readonly','');
 const published=await (await fetch(origin+'/api/v1/public/rules')).json();
 expect(published.active.title).toBe('Новая редакция тестовых правил');
 expect(published.versions.find(r=>r.id===fixtureRulesId).status).toBe('ARCHIVED');
 await page.locator('.sidebar').getByRole('button',{name:'Правила',exact:true}).click();
 await expect(reader.locator('.rules-plain-text')).toHaveText(literal);
 expect(await page.evaluate(()=>window.rulesExecuted)).toBeUndefined();
 await reader.getByLabel('Редакция правил').selectOption(fixtureRulesId);
 await expect(reader.locator('.rules-plain-text')).toContainText('Результаты публикует администратор.');
 await reader.getByRole('button',{name:'Закрыть правила'}).click();
 await page.getByRole('complementary',{name:'Версии правил'}).getByRole('button',{name:/Версия 1 · Архив/}).click();
 await page.getByRole('button',{name:'Удалить версию',exact:true}).click();
 await expect(page.getByRole('complementary',{name:'Версии правил'}).getByRole('button',{name:/Версия 1 · Архив/})).toHaveCount(0);
 expect((await fetch(origin+'/api/v1/public/rules/'+fixtureRulesId)).status).toBe(404);
 expect((await pool.query('SELECT accepted_rules_version_id FROM users WHERE tg_id=100091')).rows[0].accepted_rules_version_id).toBe(fixtureRulesId);
 await page.getByRole('button',{name:/Выйти/}).click();
 await page.route('**/api/v1/public/rules',route=>route.fulfill({json:{active:null,versions:[]}}));
 await page.reload();
 await page.getByRole('button',{name:'Регистрация на турнир',exact:true}).click();
 await expect(auth).toContainText('Правила ещё не опубликованы. Регистрация временно недоступна');
 await expect(auth.getByRole('button',{name:'Получить код через Telegram'})).toBeDisabled();
 await auth.getByRole('button',{name:'Уже участвуешь? Войти'}).click();
 await expect(auth.getByRole('button',{name:'Получить код через Telegram'})).toBeEnabled();
 expect(errors).toEqual([]);
});

test('admin tiles switch immediately despite late responses; UTC calendar and clock controls',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const pending=await post('/auth/login',{});
 await post('/bot/verify',{token:pending.token,tg_id:900001,tg_username:'PreviewAdmin'});
 const access=await (await fetch(origin+'/api/v1/auth/session/'+pending.token)).json();
 await page.goto(origin);await page.evaluate(token=>localStorage.setItem('meteora-token',token),access.access_token);await page.reload();
 await expect(page.getByRole('heading',{name:'Админка',exact:true})).toBeVisible();
 const nav=page.getByRole('navigation',{name:'Разделы базы данных'});
 let releaseWallet,releaseSettings,markWallet,markSettings;
 const walletGate=new Promise(r=>{releaseWallet=r;}),settingsGate=new Promise(r=>{releaseSettings=r;});
 const walletStarted=new Promise(r=>{markWallet=r;}),settingsStarted=new Promise(r=>{markSettings=r;});
 let lateResponses=0;
 await page.route('**/api/v1/admin/data/wallets?*',async route=>{const response=await route.fetch();markWallet();await walletGate;try{await route.fulfill({response});}catch{}lateResponses++;},{times:1});
 await page.route('**/api/v1/admin/tournament/settings',async route=>{const response=await route.fetch();markSettings();await settingsGate;try{await route.fulfill({response});}catch{}lateResponses++;},{times:1});
 const select=async(id,name)=>{await nav.getByRole('button',{name}).click();await expect(nav.getByRole('button',{name})).toHaveAttribute('aria-pressed','true');await expect(page.locator('.admin-section-content')).toHaveAttribute('data-section',id);await expect(page.locator('.admin-section-heading h2')).toHaveText(name instanceof RegExp?{'wallets':'Кошельки','scoring':'Результаты','sessions':'Сессии входа','rewards':'UID и награды','initial-users':'Реестр допуска','users':'Участники'}[id]:name);};
 await select('wallets',/^Кошельки/);await walletStarted;
 await select('scoring',/^Результаты/);await expect(page.locator('.resource-wallets')).toHaveCount(0);
 await select('sessions',/^Сессии входа/);await expect(page.getByRole('heading',{name:'Импорт результатов'})).toHaveCount(0);
 await select('settings','Настройки турнира');await settingsStarted;
 await select('rules','Правила');await expect(page.getByLabel('Текст правил',{exact:true})).toBeVisible();
 releaseWallet();releaseSettings();await expect.poll(()=>lateResponses).toBe(2);
 await expect(page.locator('.admin-section-content')).toHaveAttribute('data-section','rules');
 await expect(page.locator('.admin-data-table')).toHaveCount(0);await expect(page.getByRole('heading',{name:'Расписание турнира'})).toHaveCount(0);
 for(const[id,name]of [['initial-users',/^Реестр допуска/],['users',/^Участники/],['rewards',/^UID и награды/],['scoring',/^Результаты/],['settings','Настройки турнира'],['rules','Правила'],['settings','Настройки турнира']])await select(id,name);
 await expect(page.getByLabel('Начало регистрации · дата',{exact:true})).toBeVisible();
 await expect(page.locator('.tournament-settings')).toContainText('UTC');
 await expect(page.getByText('America/Los_Angeles',{exact:false})).toHaveCount(0);
 await page.evaluate(()=>{window.pickerTypes=[];HTMLInputElement.prototype.showPicker=function(){window.pickerTypes.push(this.type);};});
 await page.getByRole('button',{name:/Открыть календарь/}).first().click();
 await page.getByRole('button',{name:/Открыть часы/}).first().click();
 expect(await page.evaluate(()=>window.pickerTypes)).toEqual(['date']);
 const picker=page.getByRole('dialog',{name:'Начало регистрации · выбор времени UTC'});
 await expect(picker).toBeVisible();await picker.getByLabel('Начало регистрации · часы',{exact:true}).selectOption('21');await picker.getByLabel('Начало регистрации · минуты',{exact:true}).selectOption('35');
 await picker.getByRole('button',{name:'Готово',exact:true}).click();await expect(picker).toHaveCount(0);
 const time=page.getByLabel('Начало регистрации · время (UTC)',{exact:true});await expect(time).toHaveValue('21:35');await expect(time).toHaveAttribute('type','text');
 await expect(page.getByText('24 часа · UTC',{exact:true})).toHaveCount(4);
 await time.fill('25:00');expect(await time.evaluate(input=>input.checkValidity())).toBe(false);await time.fill('09:00 PM');expect(await time.evaluate(input=>input.checkValidity())).toBe(false);await time.fill('');
 const writes=[];page.on('request',r=>{if(r.method()==='POST'&&new URL(r.url()).pathname==='/api/v1/admin/tournament/settings')writes.push(r.postDataJSON());});
 await page.getByLabel('Начало регистрации · дата',{exact:true}).fill('2031-01-01');
 await page.getByRole('button',{name:'Сохранить расписание'}).click();
 expect(writes).toEqual([]);
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 expect(errors).toEqual([]);
});

test('partner link from admin, persisted nomination statuses and manual qualification roadmap',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const bind=async(tg_id,tg_username)=>{const pending=await post('/auth/login',{});await post('/bot/verify',{token:pending.token,tg_id,tg_username});const access=await(await fetch(origin+'/api/v1/auth/session/'+pending.token)).json();return access.access_token;};
 const call=async(path,body,token)=>{const r=await fetch(origin+'/api/v1'+path,{method:'POST',headers:{'content-type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(body)});expect(r.status).toBe(200);return r.json();};
 const adminToken=await bind(900001,'PreviewAdmin');
 const datesBefore=await(await fetch(origin+'/api/v1/public/tournament')).json();
 await page.goto(origin);await page.evaluate(token=>localStorage.setItem('meteora-token',token),adminToken);await page.reload();
 await page.getByRole('navigation',{name:'Разделы базы данных'}).getByRole('button',{name:'Настройки турнира'}).click();
 const link='https://partner.example/ref?source=meteora';
 await page.getByLabel('Реферальная ссылка партнёра',{exact:true}).fill(link);
 await page.getByRole('button',{name:'Сохранить ссылку',exact:true}).click();
 await expect.poll(async()=>await(await fetch(origin+'/api/v1/public/partner')).json()).toEqual({referral_url:link});
 const datesAfter=await(await fetch(origin+'/api/v1/public/tournament')).json();for(const field of ['registration_start_at','registration_end_at','start_at','end_at'])expect(datesAfter[field]).toEqual(datesBefore[field]);
 await page.getByRole('button',{name:'Личный кабинет',exact:true}).click();
 await expect(page.locator('.gift-demo-banner').getByRole('link',{name:/Выполнить условия/})).toHaveAttribute('href',link);
 const traderToken=await bind(100001,'PreviewTrader');
 await page.evaluate(token=>localStorage.setItem('meteora-token',token),traderToken);await page.reload();
 const summary=page.getByRole('region',{name:'Номинация и квалификация'}),roadmap=page.getByRole('region',{name:'Путь участника'});
 await expect(summary).toContainText('Respect Gift · допуск подтверждён');
 const partner=page.getByLabel('Указать UID аккаунта на бирже');await partner.check();
 await expect(summary).toContainText('Respect Gift · допуск подтверждён'); // Unsaved draft never changes the saved nomination.
 await page.getByRole('button',{name:'Как участвовать в Special Gift?',exact:true}).click();
 await expect(page.getByText('Вывести SOL на Ваш турнирный кошелёк',{exact:true})).toBeVisible();
 await expect(roadmap.getByRole('link',{name:/ссылке партнёра/})).toHaveAttribute('href',link);
 await page.getByLabel('UID аккаунта на бирже',{exact:true}).fill('00126100812');await page.getByLabel('Хэш вывода с биржи').fill('fixture_partner_withdrawal');
 await expect(page.getByRole('button',{name:'Сохранить профиль'})).toBeEnabled();await page.getByRole('button',{name:'Сохранить профиль'}).click();
 await expect(summary).toContainText('Special Gift · ожидает проверки партнёра');
 for(const n of [2,3,4,5])await expect(roadmap.locator(`[data-step="${n}"]`)).not.toHaveClass(/done/);
 await expect(roadmap.locator('[aria-current="step"]')).toHaveAttribute('data-step','6');
 const profile=await(await fetch(origin+'/api/v1/user/profile',{headers:{Authorization:'Bearer '+traderToken}})).json();
 await call('/admin/rewards/validate',{user_id:profile.id,exchange_uid:'00126100812',action:'VALID'},adminToken);await page.reload();
 await expect(summary).toContainText('Special Gift · подтверждён партнёром');
 for(const n of [2,3,4,5,6])await expect(roadmap.locator(`[data-step="${n}"]`)).toHaveClass(/done/);
 await call('/admin/rewards/validate',{user_id:profile.id,exchange_uid:'00126100812',action:'INVALID'},adminToken);await page.reload();
 await expect(summary).toContainText('Special Gift · квалификация не подтверждена');
 await partner.uncheck();await page.getByRole('button',{name:'Сохранить профиль'}).click();await expect(summary).toContainText('Respect Gift · ожидает проверки');
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await call('/admin/tournament/partner',{referral_url:null},adminToken);await page.reload();
 await expect(page.locator('.gift-demo-banner').getByRole('link',{name:/Выполнить условия/})).toHaveCount(0);
 await expect(page.locator('.gift-demo-banner')).toContainText('Ссылка партнёра пока не опубликована');
 expect(errors).toEqual([]);
});

test('tournament name is editable in admin, shared publicly and survives refresh',async({page,browser})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const pending=await post('/auth/login',{});await post('/bot/verify',{token:pending.token,tg_id:900001,tg_username:'PreviewAdmin'});
 const access=await(await fetch(origin+'/api/v1/auth/session/'+pending.token)).json();
 await page.goto(origin);await page.evaluate(token=>localStorage.setItem('meteora-token',token),access.access_token);await page.reload();
 await page.getByRole('navigation',{name:'Разделы базы данных'}).getByRole('button',{name:'Настройки турнира'}).click();
 const field=page.getByLabel('Название турнира',{exact:true});await expect(field).toHaveValue('PILOT TOURNAMENT');
 const scheduleBefore=await(await fetch(origin+'/api/v1/public/tournament')).json(),partnerBefore=await(await fetch(origin+'/api/v1/public/partner')).json();
 const title='PILOT 2026 · Финал';await field.fill(title);await page.getByRole('button',{name:'Сохранить название',exact:true}).click();
 await expect(page.locator('.brand>span')).toHaveText(title);
 await expect.poll(async()=>await(await fetch(origin+'/api/v1/public/tournament/name')).json()).toEqual({tournament_name:title});
 await page.reload();await page.getByRole('navigation',{name:'Разделы базы данных'}).getByRole('button',{name:'Настройки турнира'}).click();await expect(field).toHaveValue(title);
 const guest=await browser.newContext({locale:'en-US',viewport:{width:390,height:844}});
 try{const visitor=await guest.newPage();visitor.on('pageerror',e=>errors.push(e.message));await visitor.goto(origin);await expect(visitor.locator('.brand>span')).toHaveText(title);await visitor.getByRole('button',{name:'Лидерборд',exact:true}).click();await expect(visitor.locator('.leaderboard-kicker')).toContainText(title);
  const longTitle='T'.repeat(80);await field.fill(longTitle);await page.getByRole('button',{name:'Сохранить название',exact:true}).click();await expect(page.locator('.brand>span')).toHaveText(longTitle);await visitor.reload();await expect(visitor.locator('.brand>span')).toHaveText(longTitle);expect(await visitor.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 }finally{await guest.close();}
 const scheduleAfter=await(await fetch(origin+'/api/v1/public/tournament')).json();for(const key of ['registration_start_at','registration_end_at','start_at','end_at'])expect(scheduleAfter[key]).toEqual(scheduleBefore[key]);expect(await(await fetch(origin+'/api/v1/public/partner')).json()).toEqual(partnerBefore);
 await field.fill('PILOT TOURNAMENT');await page.getByRole('button',{name:'Сохранить название',exact:true}).click();await expect(page.locator('.brand>span')).toHaveText('PILOT TOURNAMENT');expect(errors).toEqual([]);
});
