import { seedRules } from './helpers/rules.mjs';
import bs58 from 'bs58';
import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import pg from 'pg';
import { SignJWT } from 'jose';
import { buildApp } from '../server/app.mjs';
import { migrate } from '../server/db.mjs';
import { loadConfig } from '../server/config.mjs';

test('configuration starts without a date and rejects unsafe demo settings',()=>{
 const env={DATABASE_URL:'postgres://localhost/test',JWT_SECRET:'j'.repeat(32),BOT_API_SECRET:'b'.repeat(32),ADMIN_TG_IDS:'1',BOT_USERNAME:'TournamentBot'};
 assert.equal(loadConfig(env).authJwtTtlSeconds,1800);assert.ok(!('tournamentStartAt' in loadConfig({...env,TOURNAMENT_START_AT:'ignored-invalid-value'})));
 assert.throws(()=>loadConfig({...env,AUTH_JWT_TTL_SECONDS:'899'}));assert.equal(loadConfig({...env,AUTH_JWT_TTL_SECONDS:'900'}).authJwtTtlSeconds,900);
 assert.throws(()=>loadConfig({...env,LOCAL_DEMO:'true',NODE_ENV:'production'}));assert.throws(()=>loadConfig({...env,LOCAL_DEMO:'true',HOST:'0.0.0.0'}));
});

test('v0.3 real PostgreSQL acceptance and concurrency',{skip:!process.env.TEST_DATABASE_URL},async t=>{
 const schema='test_'+randomUUID().replaceAll('-',''),control=new pg.Pool({connectionString:process.env.TEST_DATABASE_URL});await control.query('CREATE SCHEMA "'+schema+'"');
 const pool=new pg.Pool({connectionString:process.env.TEST_DATABASE_URL,options:'-c search_path='+schema});
 let now=new Date('2026-10-08T11:00:00Z');const start=new Date('2026-10-08T11:20:00Z');
 const config={jwtSecret:'j'.repeat(32),botApiSecret:'b'.repeat(32),adminTgIds:[900001],authJwtTtlSeconds:1800,botUsername:'TournamentBot',localDemo:false};let app;
 try {
 await migrate(pool);await migrate(pool);const rulesId=await seedRules(pool);assert.equal(Number((await pool.query("SELECT count(*) FROM information_schema.tables WHERE table_schema=$1 AND table_type='BASE TABLE'",[schema])).rows[0].count),9);
 app=buildApp({pool,config,clock:()=>now});const events=[];app.addHook('onResponse',async(req,reply)=>{if(reply.statusCode===200&&req.tournamentEvent)events.push(req.tournamentEvent);});
 const call=async(method,path,body,token,bot=false)=>{const r=await app.inject({method,url:'/api/v1'+path,...(body===undefined?{}:{payload:body}),headers:{...(token?{authorization:'Bearer '+token}:{}),...(bot?{'x-bot-secret':config.botApiSecret}:{})}});return {status:r.statusCode,body:r.json()};};
 const verify=(session,id,name=null)=>call('POST','/bot/verify',{token:session,tg_id:id,tg_username:name},null,true);
 const register=async(id,name='Trader')=>{const s=await call('POST','/auth/register',{rules_accepted:true,rules_version_id:rulesId,display_name:name});assert.equal(s.status,201);assert.equal((await call('GET','/auth/session/'+s.body.token)).body.is_used,false);const v=await verify(s.body.token,id);assert.equal(v.status,200);return {session:s.body.token,token:(await call('GET','/auth/session/'+s.body.token)).body.access_token,status:v.body.registration_status};};
 const adminUser=await register(900001,'Admin'),admin=adminUser.token,aa=await register(100001,'TraderA'),bb=await register(100002,'TraderB');
 const aId=(await call('GET','/user/profile',undefined,aa.token)).body.id,bId=(await call('GET','/user/profile',undefined,bb.token)).body.id;
 const address='11111111111111111111111111111111',address2='So11111111111111111111111111111111111111112';
 const addressB=bs58.encode(Buffer.alloc(32,2)),tokenAddresses=new Map([[aa.token,address],[bb.token,addressB]]);let fixtureAddress=10;
 const moderate=(id,action='APPROVE')=>call('POST','/admin/users/moderate',{tg_id:id,action,admin_notes:'Reviewed'},admin);
 const validate=async(id,addr,hash=null,action='VALID',reason)=>{addr??=id===aId?address:id===bId?addressB:(await pool.query('SELECT wallet_address FROM wallets WHERE user_id=$1',[id])).rows[0]?.wallet_address??address;return call('POST','/admin/wallets/validate',{user_id:id,wallet_address:addr,withdrawal_tx_hash:hash,action,...(reason?{rejection_reason:reason}:{})},admin);};
 const wallet=(token,addr,extra={})=>{if(!tokenAddresses.has(token))tokenAddresses.set(token,bs58.encode(Buffer.alloc(32,fixtureAddress++)));addr??=tokenAddresses.get(token);return call('POST','/user/wallet',{wallet_address:addr,...extra},token);};
 const score=rows=>call('POST','/admin/scoring/import',{rows},admin);
 const profile=async token=>(await call('GET','/user/profile',undefined,token)).body;
 await t.test('Telegram username matching, registration reuse, TTL and authorization',async()=>{
 assert.equal((await call('GET','/user/profile')).status,401);assert.equal((await call('GET','/admin/users',undefined,aa.token)).status,403);assert.equal((await profile(aa.token)).tg_username,null);
 await moderate(100001,'REJECT');const again=await register(100001,'Different');assert.equal(again.status,'REJECTED');assert.equal((await profile(again.token)).display_name,'TraderA');assert.equal((await verify(aa.session,100001)).body.registration_status,'REJECTED');assert.equal((await verify(aa.session,100002)).status,409);
 const pending=(await call('POST','/auth/register',{rules_accepted:true,rules_version_id:rulesId,display_name:'Parallel'})).body.token;assert.ok((await Promise.all([verify(pending,100003,''),verify(pending,100003,null)])).every(r=>r.status===200));assert.equal((await pool.query('SELECT * FROM users WHERE tg_id=100003')).rowCount,1);
 const expected=(await call('POST','/auth/register',{rules_accepted:true,rules_version_id:rulesId,display_name:'Expected',tg_username:' @Expected_User '})).body.token;
 assert.equal((await verify(expected,100007,'wrong')).body.error.code,'TELEGRAM_ACCOUNT_MISMATCH');assert.equal((await pool.query('SELECT is_used FROM pending_sessions WHERE token=$1',[expected])).rows[0].is_used,false);assert.equal((await pool.query('SELECT * FROM users WHERE tg_id=100007')).rowCount,0);assert.equal((await verify(expected,100007,'eXpEcTeD_uSeR')).status,200);
 const login=(await call('POST','/auth/login',{tg_username:'@expected_user'})).body.token;assert.equal((await verify(login,100007,'EXPECTED_USER')).status,200);
 const unknown=(await call('POST','/auth/login',{})).body.token;assert.equal((await verify(unknown,999999)).status,404);assert.equal((await call('POST','/bot/verify',{token:unknown,tg_id:100001,tg_username:null})).status,401);
 const exp=(await call('POST','/auth/register',{rules_accepted:true,rules_version_id:rulesId,display_name:'Expired'})).body.token,prior=now;now=new Date(+now+900000);assert.equal((await verify(exp,999999)).status,410);assert.equal((await call('GET','/auth/session/'+exp)).status,410);assert.equal((await pool.query('SELECT is_used FROM pending_sessions WHERE token=$1',[exp])).rows[0].is_used,false);now=prior;
 const expiredJwt=await new SignJWT({}).setProtectedHeader({alg:'HS256'}).setSubject(aId).setExpirationTime(Math.floor(+now/1000)-1).sign(new TextEncoder().encode(config.jwtSecret));assert.equal((await call('GET','/user/profile',undefined,expiredJwt)).status,401);
 });
 await t.test('initial list imports remain atomic and preserve manual moderation',async()=>{
 const path='/admin/initial-users/import',payload={rows:[{tg_id:100004,group_name:'Group',tg_username:'@member'}]};const r=await Promise.all([call('POST',path,payload,admin),call('POST',path,payload,admin)]);assert.deepEqual(r.map(v=>v.body.inserted).sort(),[0,1]);assert.deepEqual(r.map(v=>v.body.updated).sort(),[0,1]);assert.equal((await pool.query('SELECT * FROM users WHERE tg_id=100004')).rowCount,0);assert.equal((await register(100004,'TraderD')).status,'APPROVED_AUTO');
 await call('POST',path,{rows:[{tg_id:100001,group_name:'Group'}]},admin);assert.equal((await profile(aa.token)).registration_status,'REJECTED');assert.equal((await call('POST',path,{rows:[{tg_id:100009,group_name:'Good'},{tg_id:100010,group_name:''}]},admin)).status,422);assert.equal((await pool.query('SELECT * FROM initial_users WHERE tg_id=100009')).rowCount,0);assert.equal((await call('POST',path,{rows:[{tg_id:100009,group_name:'Good',admin:true}]},admin)).status,422);assert.equal((await call('POST',path,{rows:[payload.rows[0],payload.rows[0]]},admin)).status,422);
 });
 await t.test('nullable hash and atomically derived partner participation',async()=>{
 assert.equal((await call('GET','/public/tournament')).body.start_at,null);assert.equal((await call('GET','/public/tournament')).body.started,false);
 const initial=await wallet(aa.token);assert.equal(initial.status,200);assert.equal(initial.body.withdrawal_tx_hash,null);assert.equal((await profile(aa.token)).wallet_address_locked,false);
 assert.equal((await wallet(aa.token,address,{withdrawal_tx_hash:'without-uid'})).status,422);assert.equal((await wallet(aa.token,address,{reward_type:'RESPECT'})).status,422);assert.equal((await wallet(aa.token,address,{signature:'fake'})).status,422);
 assert.equal((await validate(aId)).status,200);assert.equal((await wallet(aa.token)).body.validation_status,'VALID');assert.equal((await validate(aId,address,null,'INVALID')).status,422);await validate(aId,address,null,'INVALID','Mismatch');assert.equal((await wallet(aa.token)).body.validation_status,'UNDER_REVIEW');await validate(aId);
 assert.equal((await wallet(bb.token,addressB,{exchange_uid:'00887711'})).status,422);assert.equal((await profile(bb.token)).wallet,null);assert.equal((await profile(bb.token)).rewards,null);
 assert.equal((await call('POST','/user/rewards',{exchange_uid:'00887711',withdrawal_tx_hash:'x'},bb.token)).status,422);
 const linked=await wallet(aa.token,address,{exchange_uid:'00887711',withdrawal_tx_hash:'withdrawal-1'});assert.equal(linked.body.validation_status,'UNDER_REVIEW');assert.equal((await profile(aa.token)).rewards.exchange_uid,'00887711');assert.equal((await profile(aa.token)).rewards.reward_type,'PARTNER_GIFTS');
 assert.equal((await wallet(aa.token,address,{exchange_uid:'00887711',withdrawal_tx_hash:null})).status,422);assert.equal((await call('POST','/user/rewards',{reward_type:'RESPECT',exchange_uid:null},aa.token)).status,422);
 await validate(aId,address,'withdrawal-1');await call('POST','/admin/rewards/validate',{user_id:aId,exchange_uid:'00887711',action:'VALID'},admin);assert.equal((await wallet(aa.token,address,{exchange_uid:'00887711',withdrawal_tx_hash:'withdrawal-1'})).body.validation_status,'VALID');assert.equal((await profile(aa.token)).rewards.uid_status,'VALID');
 assert.equal((await call('POST','/admin/rewards/validate',{user_id:aId,exchange_uid:'old',action:'VALID'},admin)).status,409);
 await moderate(100001);const concurrent=await Promise.all([score([{tg_id:100001,pnl:'5',initial_capital:'1000',current_capital:'1100',in_positions_amount:'300',roi_percentage:99}]),score([{tg_id:100001,pnl:'10'}])]);assert.deepEqual(concurrent.map(r=>r.body.inserted).sort(),[0,1]);
 await score([{tg_id:100001,pnl:'5',initial_capital:'1000',current_capital:'1100',in_positions_amount:'300',roi_percentage:99}]);assert.equal((await profile(aa.token)).scoring.current_capital,'1100.000000');assert.equal((await profile(aa.token)).scoring.pnl,'5.000000');assert.equal((await profile(aa.token)).scoring.roi_percentage,99);
 const changed=await wallet(aa.token,address,{withdrawal_tx_hash:'fixed'});assert.equal(changed.body.validation_status,'UNDER_REVIEW');assert.equal(changed.body.rejection_reason,null);assert.equal((await profile(aa.token)).scoring,null);assert.equal((await pool.query('SELECT pnl FROM tournament_scoring WHERE user_id=$1',[aId])).rows[0].pnl,'5.000000');assert.equal((await validate(aId,address,'withdrawal-1')).body.error.code,'WALLET_CHANGED');await validate(aId,address,'fixed');
 assert.equal((await call('GET','/public/leaderboard')).body.find(r=>r.user_id===aId).reward_tag,'SpecialPartnerGift');
 await call('POST','/user/rewards',{exchange_uid:null},aa.token);let p=await profile(aa.token);assert.equal(p.wallet.withdrawal_tx_hash,null);assert.equal(p.wallet.validation_status,'UNDER_REVIEW');assert.equal(p.rewards.uid_status,'NOT_REQUIRED');assert.equal(p.rewards.exchange_uid,null);assert.equal((await call('POST','/admin/rewards/validate',{user_id:aId,exchange_uid:'00887711',action:'VALID'},admin)).body.error.code,'UID_NOT_REQUIRED');
 assert.equal((await wallet(aa.token,address,{exchange_uid:null,withdrawal_tx_hash:'no'})).status,422);assert.equal((await wallet(aa.token,address,{exchange_uid:'',withdrawal_tx_hash:null})).status,422);await validate(aId);
 assert.equal((await call('POST','/user/rewards',{exchange_uid:'0099',withdrawal_tx_hash:'partner-hash'},aa.token)).status,200);assert.equal((await profile(aa.token)).wallet.withdrawal_tx_hash,'partner-hash');await wallet(aa.token,address,{exchange_uid:null,withdrawal_tx_hash:null});await validate(aId);
 assert.equal((await wallet(bb.token,addressB,{exchange_uid:null,withdrawal_tx_hash:null})).status,200);await validate(bId,addressB,null,'INVALID','Mismatch');
 });
 await t.test('date persistence, future validation, concurrent start guard and immutable started settings',async()=>{
 const settingsPath='/admin/tournament/settings';assert.equal((await call('POST',settingsPath,{start_at:start.toISOString()},aa.token)).status,403);assert.equal((await call('POST',settingsPath,{start_at:'2026-02-30T12:00:00Z'},admin)).status,422);assert.equal((await call('POST',settingsPath,{start_at:now.toISOString()},admin)).status,422);
 assert.equal((await call('POST',settingsPath,{start_at:start.toISOString()},admin)).status,200);assert.equal((await call('GET',settingsPath,undefined,admin)).body.start_at,start.toISOString());assert.equal((await call('POST',settingsPath,{start_at:null},admin)).status,200);assert.equal((await call('POST',settingsPath,{start_at:start.toISOString()},admin)).status,200);
 const restarted=buildApp({pool,config,clock:()=>now});try{assert.equal((await restarted.inject({method:'GET',url:'/api/v1/public/tournament'})).json().start_at,start.toISOString());}finally{await restarted.close();}
 now=new Date(+start-1000);const before=(await profile(aa.token)).wallet.id;assert.equal((await wallet(aa.token,address2)).body.id,before);assert.equal((await pool.query('SELECT pnl FROM tournament_scoring WHERE user_id=$1',[aId])).rows[0].pnl,'5.000000');assert.equal((await validate(aId)).body.error.code,'WALLET_CHANGED');await validate(aId,address2);
 // Emulate an admin's validated future-date transaction while it holds the settings row.
 const guard=await pool.connect(),other=await pool.connect();try{await guard.query('BEGIN');await guard.query('SELECT start_at FROM tournament_settings WHERE id=1 FOR UPDATE');await guard.query('UPDATE tournament_settings SET start_at=$1 WHERE id=1',[start]);now=new Date(+start+1000);let done=false;const pending=wallet(bb.token,address2).then(r=>{done=true;return r;});await new Promise(resolve=>setTimeout(resolve,50));assert.equal(done,false);await other.query('BEGIN');await other.query('SELECT id FROM users WHERE id=$1 FOR UPDATE NOWAIT',[bId]);await other.query('ROLLBACK');await guard.query('COMMIT');assert.equal((await pending).body.error.code,'WALLET_CHANGE_LOCKED');}finally{await guard.query('ROLLBACK');await other.query('ROLLBACK');guard.release();other.release();}
 assert.equal((await pool.query('SELECT * FROM tournament_scoring WHERE user_id=$1',[bId])).rowCount,0);assert.equal((await profile(aa.token)).wallet_address_locked,true);assert.equal((await profile(bb.token)).wallet.wallet_address,addressB);
 assert.equal((await wallet(aa.token,address)).body.error.code,'WALLET_CHANGE_LOCKED');assert.equal((await wallet(aa.token,address2)).body.validation_status,'VALID');assert.equal((await call('POST',settingsPath,{start_at:null},admin)).body.error.code,'TOURNAMENT_ALREADY_STARTED');assert.equal((await call('POST',settingsPath,{start_at:'2026-10-09T12:00:00Z'},admin)).status,409);
 assert.equal((await validate(bId,addressB,null,'INVALID','After start')).status,200);assert.equal((await validate(aId,address2)).status,200);const f=await register(100006,'PendingF');const fId=(await profile(f.token)).id;assert.equal((await wallet(f.token)).status,200);await validate(fId);await score([{tg_id:100006,pnl:'1000'}]);assert.equal((await profile(f.token)).scoring.pnl,'1000.000000');assert.ok(!(await call('GET','/public/leaderboard')).body.some(r=>r.user_id===fId));
 assert.equal((await call('POST','/user/wallet',{wallet_address:address,user_id:aId},f.token)).status,422);assert.equal((await wallet(f.token,'invalid!')).status,422);
 });
 await t.test('scoring precision, atomicity, numeric order, ties and public privacy',async()=>{
 for(const r of [{tg_id:100001},{tg_id:100001,pnl:null},{tg_id:100001,pnl:'1.1234567'},{tg_id:100001,pnl:'1e3'}])assert.equal((await score([r])).status,422);
 const invalid=await score([{tg_id:100001,pnl:'100'},{tg_id:777777,pnl:'1'}]);assert.equal(invalid.status,422);assert.equal(invalid.body.error.fields[0].row,2);assert.equal((await pool.query('SELECT pnl FROM tournament_scoring WHERE user_id=$1',[aId])).rows[0].pnl,'5.000000');assert.equal((await score([{tg_id:100001,pnl:'1'},{tg_id:100001,pnl:'2'}])).status,422);
 await moderate(100002);await moderate(100003);await validate(bId);const cId=(await pool.query('SELECT id FROM users WHERE tg_id=100003')).rows[0].id,dId=(await pool.query('SELECT id FROM users WHERE tg_id=100004')).rows[0].id;
 for(const id of [cId,dId])await pool.query("INSERT INTO wallets(id,user_id,wallet_address,withdrawal_tx_hash,validation_status) VALUES($1,$2,$3,NULL,'VALID')",[randomUUID(),id,bs58.encode(Buffer.alloc(32,id===cId?3:4))]);
 await score([{tg_id:100001,pnl:'2'},{tg_id:100002,pnl:'10'},{tg_id:100003,pnl:'-1'}]);let board=(await call('GET','/public/leaderboard')).body;assert.deepEqual(board.map(r=>r.pnl),['10.000000','2.000000','-1.000000',null]);assert.ok(board.every(r=>Object.keys(r).sort().join(',')==='current_capital,display_name,in_positions_amount,initial_capital,pnl,reward_tag,roi_percentage,user_id,wallet_address'));assert.ok(board.every(r=>r.reward_tag==='RespectGift'));assert.equal((await profile(aa.token)).scoring.roi_percentage,null);assert.equal((await profile(aa.token)).scoring.initial_capital,null);
 await score([{tg_id:100001,pnl:'5',roi_percentage:-90},{tg_id:100002,pnl:'5',roi_percentage:900}]);const tied=(await call('GET','/public/leaderboard')).body.filter(r=>r.pnl==='5.000000');assert.deepEqual(tied.map(r=>r.user_id),tied.map(r=>r.user_id).sort());
 await score([{tg_id:100002,pnl:'0.000000'},{tg_id:100003,pnl:'-25.500000'}]);board=(await call('GET','/public/leaderboard')).body;assert.deepEqual(board.map(r=>r.pnl),['5.000000','0.000000','-25.500000',null]);
 await moderate(100001,'REJECT');assert.ok(!(await call('GET','/public/leaderboard')).body.some(r=>r.user_id===aId));assert.equal((await pool.query('SELECT * FROM tournament_scoring WHERE user_id=$1',[aId])).rowCount,1);await moderate(100001);assert.ok((await call('GET','/public/leaderboard')).body.some(r=>r.user_id===aId));
 await validate(aId,address2,null,'INVALID','Mismatch');assert.equal((await profile(aa.token)).scoring,null);assert.equal((await call('GET','/admin/users',undefined,admin)).body.find(r=>r.id===aId).scoring.pnl,'5.000000');assert.equal((await call('POST','/admin/users/moderate',{tg_id:100001,action:'APPROVE'},admin)).status,422);
 await pool.query("UPDATE users SET registration_status='REJECTED',admin_notes='Cleanup'");assert.deepEqual((await call('GET','/public/leaderboard')).body,[]);await assert.rejects(pool.query("INSERT INTO partner_rewards(user_id,reward_type,exchange_uid,uid_status) VALUES($1,'RESPECT','uid','VALID')",[cId]));await assert.rejects(pool.query('INSERT INTO wallets(id,user_id,wallet_address) VALUES($1,$2,$3)',[randomUUID(),cId,address]));
 });
 await t.test('notification events occur only after commits and deduplicate repeated registration and wallet submissions',async()=>{
 let before=events.length;const fresh=await register(100011,'NotifyUser');const id=(await profile(fresh.token)).id;assert.deepEqual(events.slice(before),[{type:'registration',userId:id,tgId:100011}]);
 before=events.length;await register(100011,'IgnoredName');await verify(fresh.session,100011);assert.equal(events.length,before);
 before=events.length;await wallet(fresh.token);assert.deepEqual(events.slice(before),[{type:'wallet',userId:id}]);await validate(id);before=events.length;assert.equal((await wallet(fresh.token)).body.validation_status,'VALID');assert.equal(events.length,before);
 before=events.length;assert.equal((await wallet(fresh.token,tokenAddresses.get(fresh.token),{exchange_uid:'missing-hash'})).status,422);assert.equal(events.length,before);
 await pool.query("CREATE FUNCTION reject_test_wallet() RETURNS trigger LANGUAGE plpgsql AS 'BEGIN RAISE EXCEPTION ''test rollback''; END'");await pool.query('CREATE TRIGGER reject_test_wallet BEFORE UPDATE ON wallets FOR EACH ROW EXECUTE FUNCTION reject_test_wallet()');
 try{before=events.length;assert.equal((await wallet(fresh.token,tokenAddresses.get(fresh.token),{exchange_uid:'0088',withdrawal_tx_hash:'rollback'})).status,500);assert.equal(events.length,before);assert.equal((await profile(fresh.token)).wallet.withdrawal_tx_hash,null);}finally{await pool.query('DROP TRIGGER reject_test_wallet ON wallets');await pool.query('DROP FUNCTION reject_test_wallet()');}
 before=events.length;await moderate(100011);assert.deepEqual(events.slice(before),[{type:'registration_status',userId:id}]);
 before=events.length;await score([{tg_id:100011,pnl:'1'}]);assert.deepEqual(events.slice(before),[{type:'scoring',userIds:[id]}]);
 });
 await t.test('auth creation rate limits precede database writes',async()=>{const before=Number((await pool.query('SELECT count(*) FROM pending_sessions')).rows[0].count),responses=[];for(let i=0;i<25;i++)responses.push(await call('POST','/auth/login',{}));assert.ok(responses.some(r=>r.status===201));assert.equal(responses.at(-1).status,429);assert.equal(responses.at(-1).body.error.code,'RATE_LIMITED');const after=Number((await pool.query('SELECT count(*) FROM pending_sessions')).rows[0].count);assert.equal(after-before,responses.filter(r=>r.status===201).length);});
 }finally{if(app)await app.close();await pool.end();await control.query('DROP SCHEMA "'+schema+'" CASCADE');await control.end();}
});
