import { registerTournamentName } from './tournament-name.mjs';
import { registerPartner } from './partner.mjs';
import { lockRules, requireActiveRules, requirePendingConsent, registerRules } from './rules.mjs';
import { checkProfileDuplicates, assertProfileAvailable, mapDuplicateError } from './profile-duplicates.mjs';
import { readSchedule, scheduleOutput, scheduleFields } from './schedule.mjs';
import Fastify from 'fastify';
import rateLimit from '@fastify/rate-limit';
import { z } from 'zod';
import bs58 from 'bs58';
import { randomBytes, randomUUID, timingSafeEqual } from 'node:crypto';
import { SignJWT, jwtVerify } from 'jose';
import { registerAdminData } from './admin-data.mjs';
import { registerTelegramCode } from './telegram-code.mjs';
import { createAccessSessions } from './access-session.mjs';

const control=/[\u0000-\u001f\u007f]/;
const text=(max,min=1)=>z.string().trim().min(min).max(max).refine(v=>!control.test(v),'Управляющие символы запрещены');
const tg=z.number().int().positive().max(Number.MAX_SAFE_INTEGER);
const username=z.string().trim().max(256).refine(v=>!control.test(v)).nullable().transform(v=>v?.replace(/^@/,'')||null).refine(v=>v===null||v.length<=255);
const optionalText=max=>text(max,0).nullable().optional().transform(v=>v||null);
const address=text(44).refine(v=>{try{return bs58.decode(v).length===32;}catch{return false;}},'Адрес должен декодироваться в 32 байта Base58');
const hash=text(255);
const tokenSchema=z.string().regex(/^(reg_|auth_)[A-Za-z0-9_-]{43}$/);
const decimal=z.string().regex(/^-?\d{1,14}(?:\.\d{1,6})?$/,'Неверный decimal');
const capital=z.string().regex(/^\d{1,14}(?:\.\d{1,6})?$/,'Неверный decimal').nullable().optional().transform(v=>v??null);
const walletSchema=z.object({wallet_address:address,withdrawal_tx_hash:hash.nullable().optional(),exchange_uid:text(50).nullable().optional()}).strict();
const walletValidationSchema=z.object({wallet_address:address,withdrawal_tx_hash:hash.nullable()}).strict();
const rewardsSchema=z.object({exchange_uid:text(50).nullable(),withdrawal_tx_hash:hash.nullable().optional()}).strict();
const initialRow=z.object({tg_id:tg,tg_username:username.optional().transform(v=>v??null),group_name:text(100),CommunityEcosystem:optionalText(255),MeteoraPlus:optionalText(255),MeteoraPro:optionalText(255),system_notes:optionalText(100000)}).strict();
const scoreRow=z.object({tg_id:tg,pnl:decimal,initial_capital:capital,current_capital:capital,in_positions_amount:capital,lp_volume:z.string().regex(/^\d{1,14}(?:\.\d{1,6})?$/).nullable().optional(),roi_percentage:z.number().finite().nullable().optional().transform(v=>v??null)}).strict();
class ApiError extends Error {constructor(status,code,message=code,fields=[]){super(message);Object.assign(this,{status,code,fields});}}
const fail=(status,code)=>{throw new ApiError(status,code);};
function parse(schema,value){const r=schema.safeParse(value);if(r.success)return r.data;throw new ApiError(422,'VALIDATION_ERROR','Некорректные данные',r.error.issues.map(i=>{const row=i.path[0]==='rows'&&Number.isInteger(i.path[1])?i.path[1]+1:undefined;return {...(row?{row}:{}),field:i.path.filter(p=>p!=='rows'&&typeof p!=='number').join('.')||'body',message:i.message};}));}
function rows(schema,value){const result=parse(z.object({rows:z.array(schema).min(1).max(10000)}).strict(),value).rows;const seen=new Set(),fields=[];result.forEach((r,i)=>{if(seen.has(r.tg_id))fields.push({row:i+1,field:'tg_id',message:'Повтор Telegram ID'});seen.add(r.tg_id);});if(fields.length)throw new ApiError(422,'VALIDATION_ERROR','Некорректные данные',fields);return result;}
const walletOut=r=>({id:r.id,wallet_address:r.wallet_address,withdrawal_tx_hash:r.withdrawal_tx_hash,validation_status:r.validation_status,rejection_reason:r.rejection_reason});
const rewardsOut=r=>({reward_type:r.reward_type,exchange_uid:r.exchange_uid,uid_status:r.uid_status});
const joined=`SELECT u.*, t.start_at, CASE WHEN w.id IS NULL THEN NULL ELSE jsonb_build_object('id',w.id,'wallet_address',w.wallet_address,'withdrawal_tx_hash',w.withdrawal_tx_hash,'validation_status',w.validation_status,'rejection_reason',w.rejection_reason) END wallet, CASE WHEN r.user_id IS NULL THEN NULL ELSE jsonb_build_object('reward_type',r.reward_type,'exchange_uid',r.exchange_uid,'uid_status',r.uid_status) END rewards, CASE WHEN s.user_id IS NULL THEN NULL ELSE jsonb_build_object('pnl',s.pnl::text,'initial_capital',s.initial_capital::text,'current_capital',s.current_capital::text,'in_positions_amount',s.in_positions_amount::text,'roi_percentage',s.roi_percentage,'lp_volume',s.lp_volume::text) END scoring FROM users u CROSS JOIN tournament_settings t LEFT JOIN wallets w ON w.user_id=u.id LEFT JOIN partner_rewards r ON r.user_id=u.id LEFT JOIN tournament_scoring s ON s.user_id=u.id`;

export function buildApp({pool,config,clock=()=>new Date()}) {
 const app=Fastify({logger:false,bodyLimit:5*1024*1024});
 app.register(rateLimit,{global:false});
 const key=new TextEncoder().encode(config.jwtSecret);
 app.setErrorHandler((error,request,reply)=>{if(error instanceof ApiError)return reply.code(error.status).send({error:{code:error.code,message:error.message,fields:error.fields},...(error.retry_after_seconds!==undefined?{retry_after_seconds:error.retry_after_seconds}:{})});if(error.statusCode===429)return reply.code(429).send({error:{code:'RATE_LIMITED',message:'Слишком много запросов. Повторите позже',fields:[]}});if(error.statusCode===400)return reply.code(422).send({error:{code:'VALIDATION_ERROR',message:'Некорректный JSON',fields:[]}});request.log.error(error);return reply.code(500).send({error:{code:'INTERNAL_ERROR',message:'Ошибка сервера',fields:[]}});});
 const tx=async(fn,req)=>{const c=await pool.connect();delete c.tournamentEvent;try{await c.query('BEGIN');const r=await fn(c);await c.query('COMMIT');if(req&&c.tournamentEvent)req.tournamentEvent=c.tournamentEvent;return r;}catch(e){await c.query('ROLLBACK');throw mapDuplicateError(e,ApiError);}finally{delete c.tournamentEvent;c.release();}};
 const lockUser=async(c,id)=>{const r=await c.query('SELECT * FROM users WHERE id=$1 FOR UPDATE',[id]);if(!r.rows[0])fail(404,'USER_NOT_FOUND');return r.rows[0];};
 const accessSessions=createAccessSessions({pool,config,clock,tx,parse,ApiError});
 const auth=req=>accessSessions.authenticate(req);
 const admin=async(req)=>{await auth(req);if(!config.adminTgIds.includes(req.user.tgId))fail(403,'FORBIDDEN');};
 const pendingRoutes=[];
 const route=(method,url,handler,preHandler)=>pendingRoutes.push({method,url:'/api/v1'+url,handler,...(preHandler?{preHandler}:{}),...((url.startsWith('/auth/')||url.startsWith('/bot/')||url==='/user/profile-check')?{config:{rateLimit:{max:url==='/user/profile-check'?120:(url==='/auth/code/verify'||url==='/auth/code/request'||url==='/auth/renew/request')?10:(url.startsWith('/auth/session/')||url==='/auth/access')?300:url.startsWith('/bot/')?60:20,timeWindow:60000}}}:{})});
 const profile=(r,isAdmin=false)=>({id:r.id,tg_id:Number(r.tg_id),tg_username:r.tg_username,display_name:r.display_name,registration_status:r.registration_status,accepted_rules_version_id:r.accepted_rules_version_id??null,rules_accepted_at:r.rules_accepted_at?new Date(r.rules_accepted_at).toISOString():null,wallet_address_locked:!!r.wallet&&r.start_at!==null&&+clock()>=+new Date(r.start_at),wallet:r.wallet,rewards:r.rewards,scoring:isAdmin||r.wallet?.validation_status==='VALID'?r.scoring:null,...(isAdmin?{admin_notes:r.admin_notes}:{})});
 for(const [url,type] of [['/auth/register','REGISTRATION'],['/auth/login','AUTHORIZATION']])route('POST',url,async(req,reply)=>{const body=parse(type==='REGISTRATION'?z.object({display_name:text(20,3),tg_username:username.optional(),rules_accepted:z.literal(true),rules_version_id:z.string().uuid()}).strict():z.object({tg_username:username.optional()}).strict(),req.body);const created=clock();let token;for(;;){token=(type==='REGISTRATION'?'reg_':'auth_')+randomBytes(32).toString('base64url');const r=await tx(async c=>{if(type==='REGISTRATION'){if(!settingsOut(await settings(c,'FOR SHARE')).registration_open)fail(409,'REGISTRATION_NOT_OPEN');await lockRules(c);await requireActiveRules(c,body.rules_version_id,ApiError);}return c.query('INSERT INTO pending_sessions(token,session_type,display_name,created_at,expected_tg_username,rules_version_id,rules_accepted_at) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT DO NOTHING RETURNING token',[token,type,body.display_name??null,created,body.tg_username??null,body.rules_version_id??null,type==='REGISTRATION'?created:null]);});if(r.rowCount)break;}return reply.code(201).send({token,bot_link:`https://t.me/${config.botUsername}?start=${token}`,expires_at:new Date(+created+900000).toISOString()});});
 const checkSession=s=>{if(!s)fail(404,'SESSION_NOT_FOUND');if(+clock()>=+new Date(s.created_at)+900000)fail(410,'SESSION_EXPIRED');};
 route('GET','/auth/session/:token',async req=>{const token=parse(tokenSchema,req.params.token);const result=await tx(async c=>{const pending=(await c.query('SELECT * FROM pending_sessions WHERE token=$1 FOR UPDATE',[token])).rows[0];checkSession(pending);if(!pending.is_used)return null;const user=(await c.query('SELECT id,registration_status FROM users WHERE tg_id=$1',[pending.tg_id])).rows[0];if(!user)throw new Error('Bound session without user');return {session:await accessSessions.linkPending(c,pending,user.id),status:user.registration_status};});if(!result)return {is_used:false};return {is_used:true,access_token:await accessSessions.sign(result.session),token_type:'Bearer',registration_status:result.status};});
 route('POST','/bot/verify',async(req)=>{const secret=Buffer.from(req.headers['x-bot-secret']||''),expected=Buffer.from(config.botApiSecret);if(secret.length!==expected.length||!timingSafeEqual(secret,expected))fail(401,'UNAUTHORIZED');const b=parse(z.object({token:tokenSchema,tg_id:tg,tg_username:username}).strict(),req.body);return tx(async c=>{const schedule=await settings(c,'FOR SHARE');await lockRules(c);const s=(await c.query('SELECT * FROM pending_sessions WHERE token=$1 FOR UPDATE',[b.token])).rows[0];checkSession(s);if(s.expected_tg_username&&s.expected_tg_username.toLowerCase()!==b.tg_username?.toLowerCase())fail(409,'TELEGRAM_ACCOUNT_MISMATCH');if(s.is_used){if(Number(s.tg_id)!==b.tg_id)fail(409,'SESSION_ALREADY_BOUND');const u=(await c.query('SELECT registration_status FROM users WHERE tg_id=$1',[b.tg_id])).rows[0];return {status:'success',registration_status:u.registration_status};}let created=false;if(s.session_type==='REGISTRATION'&&!(await c.query('SELECT id FROM users WHERE tg_id=$1',[b.tg_id])).rowCount){if(!settingsOut(schedule).registration_open)fail(409,'REGISTRATION_NOT_OPEN');await requirePendingConsent(c,s,ApiError);}if(s.session_type==='REGISTRATION')created=(await c.query(`INSERT INTO users(id,tg_id,tg_username,display_name,registration_status,accepted_rules_version_id,rules_accepted_at) SELECT $1,$2,$3,$4,CASE WHEN EXISTS(SELECT 1 FROM initial_users WHERE tg_id=$2) THEN 'APPROVED_AUTO'::registration_status ELSE 'PENDING_VALIDATION'::registration_status END,$5,$6 ON CONFLICT(tg_id) DO NOTHING`,[randomUUID(),b.tg_id,b.tg_username,s.display_name,s.rules_version_id,s.rules_accepted_at])).rowCount===1;const u=(await c.query('SELECT * FROM users WHERE tg_id=$1 FOR UPDATE',[b.tg_id])).rows[0];if(!u)fail(404,'USER_NOT_REGISTERED');await c.query('UPDATE users SET tg_username=$2 WHERE id=$1',[u.id,b.tg_username]);await c.query('UPDATE pending_sessions SET tg_id=$2,is_used=true WHERE token=$1',[b.token,b.tg_id]);if(created)c.tournamentEvent={type:'registration',userId:u.id,tgId:b.tg_id};return {status:'success',registration_status:u.registration_status};},req);});
 const settings=readSchedule;
 const settingsOut=r=>scheduleOutput(r,clock());
 const saveRewards=async(c,id,uid)=>{const old=(await c.query('SELECT * FROM partner_rewards WHERE user_id=$1',[id])).rows[0];const type=uid===null?'RESPECT':'PARTNER_GIFTS';if(old&&old.reward_type===type&&old.exchange_uid===uid)return rewardsOut(old);return rewardsOut((await c.query('INSERT INTO partner_rewards(user_id,reward_type,exchange_uid,uid_status) VALUES($1,$2,$3,$4) ON CONFLICT(user_id) DO UPDATE SET reward_type=EXCLUDED.reward_type,exchange_uid=EXCLUDED.exchange_uid,uid_status=EXCLUDED.uid_status RETURNING *',[id,type,uid,uid===null?'NOT_REQUIRED':'UNDER_REVIEW'])).rows[0]);};
 const saveWallet=async(c,id,old,addr,withdrawal)=>{if(old&&old.wallet_address===addr&&old.withdrawal_tx_hash===withdrawal&&old.validation_status!=='INVALID')return walletOut(old);c.tournamentEvent={type:'wallet',userId:id};return walletOut((await c.query("INSERT INTO wallets(id,user_id,wallet_address,withdrawal_tx_hash) VALUES($1,$2,$3,$4) ON CONFLICT(user_id) DO UPDATE SET wallet_address=EXCLUDED.wallet_address,withdrawal_tx_hash=EXCLUDED.withdrawal_tx_hash,validation_status='UNDER_REVIEW',rejection_reason=NULL RETURNING *",[randomUUID(),id,addr,withdrawal])).rows[0]);};
 const conditionalHash=(uid,input,oldHash)=>{if(uid===null){if(input!==undefined&&input!==null)throw new ApiError(422,'VALIDATION_ERROR','Хэш вывода допускается только при UID',[{field:'withdrawal_tx_hash',message:'Без UID хэш должен быть null'}]);return null;}const effective=input===undefined?oldHash:input;if(!effective)throw new ApiError(422,'VALIDATION_ERROR','Для UID обязателен хэш вывода',[{field:'withdrawal_tx_hash',message:'Укажите непустой хэш'}]);return effective;};
 route('GET','/public/tournament',async()=>settingsOut(await settings(pool)));
 route('GET','/admin/tournament/settings',async()=>settingsOut(await settings(pool)),admin);
 route('POST','/admin/tournament/settings',async req=>{
  const date=z.string().refine(v=>/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,3})?Z$/.test(v)&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString().slice(0,19)===v.slice(0,19),'Неверная UTC дата').nullable().optional();
  const body=parse(z.object(Object.fromEntries(scheduleFields.map(field=>[field,date]))).strict().refine(v=>Object.keys(v).length>0,'Укажите хотя бы одну дату'),req.body);
  return tx(async c=>{
   const old=await settings(c,'FOR UPDATE'),current=clock(),next={...old,...body};
   for(const field of scheduleFields){
    const changed=Object.hasOwn(body,field)&&(old[field]===null?body[field]!==null:body[field]===null||+new Date(old[field])!==Date.parse(body[field]));
    if(changed&&old[field]!==null&&+current>=+new Date(old[field]))fail(409,field==='start_at'?'TOURNAMENT_ALREADY_STARTED':'SCHEDULE_DATE_LOCKED');
    if(changed&&field==='start_at'&&body[field]!==null&&Date.parse(body[field])<=+current)throw new ApiError(422,'VALIDATION_ERROR','Дата должна быть в будущем',[{field,message:'Дата должна быть в будущем'}]);
   }
   const value=field=>next[field]===null?null:+new Date(next[field]);
   if(value('registration_start_at')!==null&&value('registration_end_at')!==null&&value('registration_start_at')>=value('registration_end_at')||value('end_at')!==null&&(value('start_at')===null||value('start_at')>=value('end_at')||value('registration_start_at')!==null&&value('registration_start_at')>=value('end_at')||value('registration_end_at')!==null&&value('registration_end_at')>value('end_at')))throw new ApiError(422,'VALIDATION_ERROR','Неверный порядок дат',[{field:'body',message:'Проверьте порядок начала и конца интервалов'}]);
   return settingsOut((await c.query('UPDATE tournament_settings SET registration_start_at=$1,registration_end_at=$2,start_at=$3,end_at=$4 WHERE id=1 RETURNING *',scheduleFields.map(field=>next[field]))).rows[0]);
  },req);
 },admin);
 route('GET','/public/stats',async()=>{
  const row=(await pool.query("SELECT count(*) participant_count,sum(s.initial_capital)::text initial_capital,sum(s.current_capital)::text current_capital,sum(s.pnl)::text pnl,sum(s.lp_volume)::text lp_volume,count(s.pnl) scored_participant_count,count(s.current_capital) capital_participant_count,count(s.lp_volume) lp_participant_count FROM users u JOIN wallets w ON w.user_id=u.id AND w.validation_status='VALID' LEFT JOIN tournament_scoring s ON s.user_id=u.id WHERE u.registration_status IN ('APPROVED_AUTO','APPROVED_MANUAL')")).rows[0];
  for(const field of ['participant_count','scored_participant_count','capital_participant_count','lp_participant_count'])row[field]=Number(row[field]);
  return {...row,server_time:clock().toISOString()};
 });
 route('GET','/user/profile',async req=>profile((await pool.query(joined+' WHERE u.id=$1',[req.user.id])).rows[0]),auth);
 route('GET','/admin/users',async()=> (await pool.query(joined+' ORDER BY u.id')).rows.map(r=>profile(r,true)),admin);
 route('GET','/public/leaderboard',async()=> (await pool.query('SELECT * FROM leaderboard ORDER BY pnl DESC NULLS LAST,user_id ASC')).rows);
 route('POST','/user/profile-check',async req=>{const body=parse(z.object({wallet_address:address.optional(),exchange_uid:text(50).optional()}).strict().refine(v=>Object.keys(v).length>0,'Укажите поле для проверки'),req.body);return checkProfileDuplicates(pool,req.user.id,body);},auth);
 route('POST','/user/wallet',async req=>{const b=parse(walletSchema,req.body);return tx(async c=>{const tournament=await settings(c,'FOR SHARE');await lockUser(c,req.user.id);const old=(await c.query('SELECT * FROM wallets WHERE user_id=$1',[req.user.id])).rows[0];if(old&&old.wallet_address!==b.wallet_address&&tournament.start_at!==null&&+clock()>=+new Date(tournament.start_at))fail(409,'WALLET_CHANGE_LOCKED');const reward=(await c.query('SELECT exchange_uid FROM partner_rewards WHERE user_id=$1',[req.user.id])).rows[0];const uid=b.exchange_uid===undefined?reward?.exchange_uid??null:b.exchange_uid;const withdrawal=conditionalHash(uid,b.withdrawal_tx_hash,old?.withdrawal_tx_hash??null);await assertProfileAvailable(c,req.user.id,{wallet_address:b.wallet_address,exchange_uid:uid},ApiError);const result=await saveWallet(c,req.user.id,old,b.wallet_address,withdrawal);if(b.exchange_uid!==undefined)await saveRewards(c,req.user.id,uid);return result;},req);},auth);
 route('POST','/user/rewards',async req=>{const b=parse(rewardsSchema,req.body);return tx(async c=>{await lockUser(c,req.user.id);const old=(await c.query('SELECT * FROM wallets WHERE user_id=$1',[req.user.id])).rows[0];if(b.exchange_uid!==null&&!old)throw new ApiError(422,'VALIDATION_ERROR','Сначала укажите кошелёк',[{field:'exchange_uid',message:'UID требует кошелёк'}]);const withdrawal=conditionalHash(b.exchange_uid,b.withdrawal_tx_hash,old?.withdrawal_tx_hash??null);await assertProfileAvailable(c,req.user.id,{exchange_uid:b.exchange_uid},ApiError);if(old&&old.withdrawal_tx_hash!==withdrawal)await saveWallet(c,req.user.id,old,old.wallet_address,withdrawal);return saveRewards(c,req.user.id,b.exchange_uid);},req);},auth);
 route('POST','/admin/users/moderate',async req=>{const b=parse(z.object({tg_id:tg,action:z.enum(['APPROVE','REJECT']),admin_notes:text(100000)}).strict(),req.body);return tx(async c=>{const u=(await c.query('SELECT * FROM users WHERE tg_id=$1 FOR UPDATE',[b.tg_id])).rows[0];if(!u)fail(404,'USER_NOT_FOUND');const status=b.action==='APPROVE'?'APPROVED_MANUAL':'REJECTED';await c.query('UPDATE users SET registration_status=$2,admin_notes=$3 WHERE id=$1',[u.id,status,b.admin_notes]);c.tournamentEvent={type:'registration_status',userId:u.id};return {tg_id:b.tg_id,registration_status:status,admin_notes:b.admin_notes};},req);},admin);
 route('POST','/admin/wallets/validate',async req=>{const b=parse(walletValidationSchema.extend({user_id:z.string().uuid(),action:z.enum(['VALID','INVALID']),rejection_reason:text(100000).nullable().optional()}).superRefine((v,c)=>{if(v.action==='INVALID'&&!v.rejection_reason||v.action==='VALID'&&v.rejection_reason!==null&&v.rejection_reason!==undefined)c.addIssue({code:'custom',path:['rejection_reason'],message:'Причина нужна только для INVALID'});}),req.body);return tx(async c=>{await lockUser(c,b.user_id);const w=(await c.query('SELECT * FROM wallets WHERE user_id=$1',[b.user_id])).rows[0];if(!w)fail(404,'WALLET_NOT_FOUND');if(w.wallet_address!==b.wallet_address||w.withdrawal_tx_hash!==b.withdrawal_tx_hash)fail(409,'WALLET_CHANGED');c.tournamentEvent={type:'wallet_status',userId:b.user_id};return walletOut((await c.query('UPDATE wallets SET validation_status=$2,rejection_reason=$3 WHERE user_id=$1 RETURNING *',[b.user_id,b.action,b.rejection_reason??null])).rows[0]);},req);},admin);
 route('POST','/admin/rewards/validate',async req=>{const b=parse(z.object({user_id:z.string().uuid(),exchange_uid:text(50),action:z.enum(['VALID','INVALID'])}).strict(),req.body);return tx(async c=>{await lockUser(c,b.user_id);const r=(await c.query('SELECT * FROM partner_rewards WHERE user_id=$1',[b.user_id])).rows[0];if(!r)fail(404,'REWARDS_NOT_FOUND');if(r.reward_type==='RESPECT')fail(409,'UID_NOT_REQUIRED');if(r.exchange_uid!==b.exchange_uid)fail(409,'UID_CHANGED');c.tournamentEvent={type:'uid_status',userId:b.user_id};return rewardsOut((await c.query('UPDATE partner_rewards SET uid_status=$2 WHERE user_id=$1 RETURNING *',[b.user_id,b.action])).rows[0]);},req);},admin);
 route('POST','/admin/initial-users/import',async req=>{const data=rows(initialRow,req.body);return tx(async c=>{await c.query('LOCK TABLE initial_users IN SHARE ROW EXCLUSIVE MODE');const count=(await c.query('SELECT tg_id FROM initial_users WHERE tg_id=ANY($1::bigint[])',[data.map(r=>r.tg_id)])).rowCount;for(const r of data)await c.query(`INSERT INTO initial_users(tg_id,tg_username,group_name,subgroup_1,subgroup_2,subgroup_3,system_notes) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(tg_id) DO UPDATE SET tg_username=EXCLUDED.tg_username,group_name=EXCLUDED.group_name,subgroup_1=EXCLUDED.subgroup_1,subgroup_2=EXCLUDED.subgroup_2,subgroup_3=EXCLUDED.subgroup_3,system_notes=EXCLUDED.system_notes`,[r.tg_id,r.tg_username,r.group_name,r.CommunityEcosystem,r.MeteoraPlus,r.MeteoraPro,r.system_notes]);return {inserted:data.length-count,updated:count};},req);},admin);
 route('POST','/admin/scoring/import',async req=>{const data=rows(scoreRow,req.body);return tx(async c=>{const users=(await c.query('SELECT id,tg_id FROM users WHERE tg_id=ANY($1::bigint[]) ORDER BY id FOR UPDATE',[data.map(r=>r.tg_id)])).rows;const map=new Map(users.map(u=>[Number(u.tg_id),u.id]));const fields=data.flatMap((r,i)=>map.has(r.tg_id)?[]:[{row:i+1,field:'tg_id',message:'Пользователь не зарегистрирован'}]);if(fields.length)throw new ApiError(422,'VALIDATION_ERROR','Некорректные данные',fields);const count=(await c.query('SELECT user_id FROM tournament_scoring WHERE user_id=ANY($1::uuid[])',[users.map(u=>u.id)])).rowCount;for(const r of data)await c.query(`INSERT INTO tournament_scoring(user_id,pnl,initial_capital,current_capital,in_positions_amount,roi_percentage,lp_volume) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(user_id) DO UPDATE SET pnl=EXCLUDED.pnl,initial_capital=EXCLUDED.initial_capital,current_capital=EXCLUDED.current_capital,in_positions_amount=EXCLUDED.in_positions_amount,roi_percentage=EXCLUDED.roi_percentage,lp_volume=CASE WHEN $8 THEN EXCLUDED.lp_volume ELSE tournament_scoring.lp_volume END`,[map.get(r.tg_id),r.pnl,r.initial_capital,r.current_capital,r.in_positions_amount,r.roi_percentage,r.lp_volume??null,Object.hasOwn(r,'lp_volume')]);c.tournamentEvent={type:'scoring',userIds:users.map(u=>u.id)};return {inserted:data.length-count,updated:count};},req);},admin);
 registerTournamentName({route,admin,pool,tx,parse});
 registerPartner({route,admin,pool,tx,parse});
 registerRules({route,admin,pool,clock,tx,parse,ApiError});
 registerAdminData({route,admin,pool,clock,parse,ApiError});
 registerTelegramCode({route,pool,config,clock,tx,parse,ApiError,tg,username,tokenSchema,accessSessions});
 accessSessions.register(route,app);
 // Register after plugin initialization so its onRoute hook sees every API route.
 app.after(error=>{if(error)throw error;for(const definition of pendingRoutes)app.route(definition);});
 return app;
}
