import React,{useEffect,useRef,useState} from 'react';
import {RefreshCw,ChevronLeft,ChevronRight,Database} from 'lucide-react';
import {request,ApiError,decimal} from './api';
import {Badge,ErrorBox} from './main';
import './admin.css';
import {formatUtc} from './utc';
export const adminSections=[{id:'users',label:'Участники',count:'users'},{id:'initial-users',label:'Реестр допуска',count:'initial_users'},{id:'wallets',label:'Кошельки',count:'wallets'},{id:'rewards',label:'UID и награды',count:'partner_rewards'},{id:'scoring',label:'Результаты',count:'tournament_scoring'},{id:'sessions',label:'Сессии входа',count:'pending_sessions'},{id:'settings',label:'Настройки турнира'},{id:'rules',label:'Правила'}];
const columns={
 'initial-users':[['tg_id','Telegram ID','number'],['tg_username','Telegram username','nullable'],['group_name','Группа','string'],['subgroup_1','Подгруппа 1','nullable'],['subgroup_2','Подгруппа 2','nullable'],['subgroup_3','Подгруппа 3','nullable'],['system_notes','Заметки','nullable']],
 wallets:[['display_name','Участник','string'],['tg_id','Telegram ID','number'],['tg_username','Telegram username','nullable'],['wallet_address','Адрес кошелька','string'],['withdrawal_tx_hash','Хэш вывода','nullable'],['validation_status','Проверка кошелька','wallet-status'],['rejection_reason','Причина отклонения','nullable'],['id','ID кошелька','string'],['user_id','ID участника','string']],
 rewards:[['display_name','Участник','string'],['tg_id','Telegram ID','number'],['tg_username','Telegram username','nullable'],['reward_type','Тип участия','reward'],['exchange_uid','UID аккаунта на бирже','nullable'],['uid_status','Проверка UID','uid-status'],['user_id','ID участника','string']],
 scoring:[['display_name','Участник','string'],['tg_id','Telegram ID','number'],['tg_username','Telegram username','nullable'],['pnl','PNL','decimal'],['initial_capital','Начальный капитал','nullable-decimal'],['current_capital','Текущий капитал','nullable-decimal'],['in_positions_amount','В позициях','nullable-decimal'],['lp_volume','Оборот LP · SOL','nonnegative-decimal'],['roi_percentage','ROI · справочно','roi'],['user_id','ID участника','string']],
 sessions:[['session_type','Тип сессии','session'],['display_name','Имя в турнире','nullable'],['expected_tg_username','Ожидаемый username','nullable'],['tg_id','Telegram ID','nullable-number'],['is_used','Подтверждена','boolean'],['expired','Истекла','boolean'],['created_at','Создана','date'],['expires_at','Истекает','date']]
};
const enumSets={'wallet-status':['VALID','INVALID','UNDER_REVIEW'],'uid-status':['VALID','INVALID','UNDER_REVIEW','NOT_REQUIRED'],reward:['RESPECT','PARTNER_GIFTS'],session:['REGISTRATION','AUTHORIZATION']};
function valid(v,type){if(type==='nullable')return v===null||typeof v==='string';if(type==='nullable-number')return v===null||typeof v==='number'&&Number.isSafeInteger(v);if(type==='number')return typeof v==='number'&&Number.isSafeInteger(v);if(type==='string')return typeof v==='string';if(type==='boolean')return typeof v==='boolean';if(type==='date')return typeof v==='string'&&Number.isFinite(Date.parse(v));if(type==='roi')return v===null||typeof v==='number'&&Number.isFinite(v);if(type==='nonnegative-decimal')return v===null||typeof v==='string'&&/^\d+(\.\d+)?$/.test(v);if(type==='decimal'||type==='nullable-decimal')return type==='nullable-decimal'&&v===null||typeof v==='string'&&/^-?\d+(\.\d+)?$/.test(v);return enumSets[type]?.includes(v);}
function validate(data,resource){if(!data||!Array.isArray(data.rows)||!Number.isInteger(data.total)||data.total<0||!Number.isInteger(data.page)||data.page<1||!Number.isInteger(data.limit)||data.limit<1)throw new ApiError('Контракт API нарушен: ожидались rows, total, page и limit');for(const row of data.rows){for(const [key,,type] of columns[resource])if(!valid(row[key],type))throw new ApiError(`Контракт API нарушен: ожидалось поле ${key}`);if(resource==='sessions'&&['token','bot_link','access_token'].some(k=>k in row))throw new ApiError('Контракт API нарушен: ответ сессий содержит секретные поля');}return data;}
function cell(value,type){if(value===null)return '—';if(type.endsWith('status'))return <Badge value={value}/>;if(type.includes('decimal'))return decimal(value);if(type==='roi')return `${value}%`;if(type==='date')return formatUtc(value);if(type==='boolean')return value?'Да':'Нет';if(type==='session')return value==='REGISTRATION'?'Регистрация':'Вход';if(type==='reward')return value==='RESPECT'?'RespectGift':'Партнёрское участие';return String(value);}
export function AdminSummary({token,revision,section,setSection}){const[data,setData]=useState(null);const[error,setError]=useState(null);useEffect(()=>{const controller=new AbortController();setError(null);setData(null);request('/admin/data/summary',{token,signal:controller.signal}).then(d=>{for(const s of adminSections.filter(s=>s.count))if(!Number.isInteger(d[s.count])||d[s.count]<0)throw new ApiError(`Контракт API нарушен: ожидалось поле ${s.count}`);if(!controller.signal.aborted)setData(d);}).catch(e=>{if(!controller.signal.aborted&&e.name!=='AbortError')setError(e);});return()=>controller.abort();},[token,revision]);return <><div className="admin-data-note"><Database size={17}/><span>Данные приложения · 8 разделов · доступ администратора</span></div><ErrorBox error={error}/><nav className="admin-data-tabs" aria-label="Разделы базы данных">{adminSections.map(s=><button type="button" aria-pressed={section===s.id} key={s.id} className={section===s.id?'active':''} onClick={()=>setSection(s.id)}><span>{s.label}</span>{s.count&&<b>{data?data[s.count]:'—'}</b>}</button>)}</nav></>}
export function AdminDataTable({resource,token,revision}){const[data,setData]=useState(null);const[search,setSearch]=useState('');const[query,setQuery]=useState('');const[page,setPage]=useState(1);const[limit,setLimit]=useState(25);const[loading,setLoading]=useState(true);const[error,setError]=useState(null);const[refresh,setRefresh]=useState(0);const generation=useRef(0);
useEffect(()=>{const normalized=search.trim();if(normalized===query)return;const timer=setTimeout(()=>{setQuery(normalized);setPage(1);},350);return()=>clearTimeout(timer);},[search,query]);
useEffect(()=>{const g=++generation.current;const controller=new AbortController();setLoading(true);setError(null);setData(null);const params=new URLSearchParams({page:String(page),limit:String(limit),search:query});request(`/admin/data/${resource}?${params}`,{token,signal:controller.signal}).then(r=>{const d=validate(r,resource);if(g===generation.current){setData(d);if(page>1&&d.rows.length===0&&d.total>0)setPage(Math.max(1,Math.ceil(d.total/limit)));}}).catch(e=>{if(g===generation.current&&e.name!=='AbortError')setError(e);}).finally(()=>{if(g===generation.current)setLoading(false);});return()=>{generation.current++;controller.abort();};},[resource,token,page,limit,query,revision,refresh]);
const totalPages=data?Math.max(1,Math.ceil(data.total/data.limit)):1;return <section className="admin-data-section"><div className="admin-data-toolbar"><label className="field admin-data-search"><span>Поиск по данным раздела</span><input maxLength={100} value={search} placeholder="Введите имя, ID или значение" onChange={e=>setSearch(e.target.value)}/></label><label className="admin-data-limit"><span>Строк на странице</span><select value={limit} onChange={e=>{setLimit(Number(e.target.value));setPage(1);}}>{[25,50,100].map(n=><option key={n}>{n}</option>)}</select></label><button className="icon-button" title="Обновить данные" disabled={loading} onClick={()=>setRefresh(n=>n+1)}><RefreshCw size={17}/></button></div><ErrorBox error={error}/><div className="admin-data-table-wrap" data-resource={resource} tabIndex={0} aria-label="Таблица данных с горизонтальной прокруткой"><table className={`admin-data-table resource-${resource}`}><thead><tr>{columns[resource].map(([k,label])=><th key={k}>{label}</th>)}</tr></thead><tbody>{data?.rows.map((row,i)=><tr key={row.id||row.user_id||`${page}-${i}`}>{columns[resource].map(([k,,type])=><td key={k} className={type.includes('decimal')||type==='roi'?'data-numeric':''}>{cell(row[k],type)}</td>)}</tr>)}</tbody></table>{loading&&<div className="empty" role="status">Загружаем данные…</div>}{!loading&&!error&&data?.rows.length===0&&<div className="empty">{query?'По этому запросу записей нет':'В этом разделе пока нет записей'}</div>}</div><div className="admin-data-pagination"><span>{data?`Всего записей: ${data.total} · Страница ${data.page} из ${totalPages}`:'Ожидаем данные'}</span><div><button className="button secondary small" disabled={loading||page===1} onClick={()=>setPage(n=>n-1)}><ChevronLeft size={14}/>Назад</button><button className="button secondary small" disabled={loading||!data||page>=totalPages} onClick={()=>setPage(n=>n+1)}>Далее<ChevronRight size={14}/></button></div></div></section>}
