import React,{useEffect,useRef,useState} from 'react';
import bs58 from 'bs58';
import {CheckCircle2,AlertCircle,LoaderCircle} from 'lucide-react';
import {request,ApiError} from './api';
const duplicateMessages={wallet_address:'Этот кошелёк уже зарегистрирован другим участником',exchange_uid:'Этот UID уже зарегистрирован другим участником'};
function validAddress(value){try{return value.length>0&&value.length<=44&&bs58.decode(value).length===32;}catch{return false;}}
export function useProfileAvailability({address,uid,partner,token,profile}){const wallet=address.trim(),exchange=partner?uid.trim():'';const walletValid=validAddress(wallet),uidValid=!!exchange&&exchange.length<=50;const key=JSON.stringify([wallet,exchange,partner]);const[result,setResult]=useState(null);const generation=useRef(0);
useEffect(()=>{const g=++generation.current;const controller=new AbortController();setResult(null);if(!walletValid&&!uidValid)return()=>controller.abort();const timer=setTimeout(async()=>{try{const body={...(walletValid?{wallet_address:wallet}:{}),...(uidValid?{exchange_uid:exchange}:{})};const data=await request('/user/profile-check',{token,body,signal:controller.signal});for(const field of ['wallet_address','exchange_uid']){const expected=field in body;if(expected?!(data[field]&&typeof data[field].available==='boolean'):data[field]!==null)throw new ApiError(`Контракт API нарушен: ожидалось поле ${field}`);}if(g===generation.current)setResult({key,profile,wallet_address:data.wallet_address?data.wallet_address.available?'available':'duplicate':null,exchange_uid:data.exchange_uid?data.exchange_uid.available?'available':'duplicate':null});}catch(e){if(e.name!=='AbortError'&&g===generation.current)setResult({key,profile,wallet_address:walletValid?'unknown':null,exchange_uid:uidValid?'unknown':null});}},500);return()=>{generation.current++;controller.abort();clearTimeout(timer);};},[wallet,exchange,partner,token,profile]);
function state(field){const valid=field==='wallet_address'?walletValid:uidValid;if(!valid)return (field==='wallet_address'?wallet:exchange)?'invalid':null;return result?.key===key&&result.profile===profile?result[field]:'checking';}
const walletState=state('wallet_address'),uidState=state('exchange_uid');function conflict(field){setResult(current=>({...(current?.key===key&&current.profile===profile?current:{key,profile,wallet_address:walletValid?'unknown':null,exchange_uid:uidValid?'unknown':null}),[field]:'duplicate'}));}
return {walletState,uidState,blocked:[walletState,uidState].some(s=>s==='checking'||s==='duplicate'||s==='invalid'),conflict};}
export function Availability({field,state}){const text=state==='checking'?'Проверяем на дубликаты…':state==='duplicate'?duplicateMessages[field]:state==='available'?'Проверено: дубликатов нет':state==='invalid'?field==='wallet_address'?'Неверный формат: укажите адрес Solana в Base58, декодируемый в 32 байта.':'UID аккаунта на бирже должен содержать не более 50 символов.':state==='unknown'?'Не удалось проверить уникальность. При сохранении сервер проверит данные повторно.':'';const Icon=state==='checking'?LoaderCircle:state==='available'?CheckCircle2:AlertCircle;return <div id={`availability-${field}`} className={`field-availability ${state||'empty'}`} data-field={field} aria-live="polite">{text&&<><Icon size={17} aria-hidden="true"/><span>{text}</span></>}</div>}
