import React,{useEffect,useRef,useState} from 'react';
import {request,ApiError} from './api';
import {tokenExpiry} from './session';
import {ErrorBox} from './main';
export function SessionControl({token,onRenew,onExpire,onReady}){const[remaining,setRemaining]=useState(Math.max(0,Math.ceil((tokenExpiry(token)-Date.now())/1000)));const[waiting,setWaiting]=useState(false);const[busy,setBusy]=useState(false);const[cooldown,setCooldown]=useState(0);const[error,setError]=useState(null);const deadline=useRef(tokenExpiry(token));const offset=useRef(0);const waitingRef=useRef(false);const cooldownAt=useRef(0);const refreshRef=useRef(null);
useEffect(()=>{let stopped=false,running=false,lastPoll=0,finalStarted=false,accessConfirmed=false;const controller=new AbortController();deadline.current=tokenExpiry(token);offset.current=0;async function refresh(final=false){if(stopped||running)return;running=true;lastPoll=Date.now();try{const r=await request('/auth/access',{token,signal:controller.signal});if(stopped)return;const exp=Date.parse(r.expires_at),server=Date.parse(r.server_time);if(!Number.isFinite(exp)||!Number.isFinite(server)||typeof r.access_token!=='string'||r.token_type!=='Bearer'||!(r.renewal===null||r.renewal&&Number.isFinite(Date.parse(r.renewal.expires_at))))throw new ApiError('Контракт API нарушен: ожидалось состояние сессии');accessConfirmed=true;offset.current=server-Date.now();deadline.current=exp;setRemaining(Math.max(0,Math.ceil((exp-server)/1000)));waitingRef.current=!!r.renewal;setWaiting(!!r.renewal);if(r.access_token!==token)onRenew(r.access_token);onReady();if(exp<=server){onExpire();return;}finalStarted=false;}catch(e){if(stopped)return;if(e.status===401||final){onExpire();return;}setError(e);}finally{running=false;}}
refreshRef.current=refresh;refresh();const timer=setInterval(()=>{const left=deadline.current-(Date.now()+offset.current);setRemaining(Math.max(0,Math.ceil(left/1000)));setCooldown(Math.max(0,Math.ceil((cooldownAt.current-Date.now())/1000)));if(left<=0){if(!finalStarted&&!running){finalStarted=true;refresh(true);}return;}if(!running&&(waitingRef.current&&Date.now()-lastPoll>=3000||(left<=300000||!accessConfirmed)&&Date.now()-lastPoll>=15000))refresh();},1000);return()=>{stopped=true;controller.abort();clearInterval(timer);refreshRef.current=null;};},[token]);
async function renew(){if(busy||cooldown)return;setBusy(true);setError(null);try{const r=await request('/auth/renew/request',{token,body:{}});if(r.status!=='requested'||!Number.isFinite(Date.parse(r.expires_at))||!Number.isInteger(r.retry_after_seconds))throw new ApiError('Контракт API нарушен: ожидался запрос продления');cooldownAt.current=Date.now()+r.retry_after_seconds*1000;setCooldown(r.retry_after_seconds);waitingRef.current=true;setWaiting(true);await refreshRef.current?.();}catch(e){setError(e);if(e.status===401)await refreshRef.current?.(true);}finally{setBusy(false);}}
if(remaining>300)return null;return <aside className="session-banner" aria-label="Продление сессии"><div><b>Сессия завершится через {Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')}</b><p>Подтвердите продолжение через бота, чтобы остаться в кабинете без повторного входа.</p>{waiting&&<p>Откройте <a href="https://t.me/lptournamentsupport_bot" target="_blank" rel="noopener noreferrer">@lptournamentsupport_bot</a> и нажмите «Подтвердить сессию на сайте». Нажатие кнопки сайта само не продлевает вход.</p>}<ErrorBox error={error}/></div><button className="button small" disabled={busy||cooldown>0} onClick={renew}>{busy?'Отправляем запрос…':cooldown?`Повтор через ${cooldown} с`:'Продолжить через Telegram'}</button></aside>}
